### ISSUE TITLE
Unexpected Behavior with Work Profile Apps

### ISSUE THREAD

**Issue by rifaidev** [ukanth/afwall#661] opened 2017-01-16 13:01 UTC
My device [work profile](https://support.google.com/work/android/answer/6191949?hl=en) apps are not working under Allow Mode even after checking (allowing) all list apps (core, system, user). It only work when allowing -10 (Any app) which supposed to be same as selecting all apps.

From the firewall log I can see that work profile apps are using same normal apps UID plus 11 added at the beginning. E.g. com.google.android.gm(10069) normal Gmail App, com.google.android.gm(1110069) work profile Gmail App.

I'm using Nexus 5X, Android 7.1.1 updated to latest security patch level January 5, 2017.

**Comment by ukanth** [comment] 2017-02-24 02:55
Duplicate of #271

**Closed as completed by ukanth** 2017-02-24 02:55 UTC
