### ISSUE TITLE
mnl_cb_run: Operation not permitted

### ISSUE THREAD

**Issue by abidal3** [ukanth/afwall#842] opened 2018-06-13 17:41 UTC
Log:
/data/user/0/dev.ukanth.ufirewall/app_bin/nflog 40
mnl_cb_run: Operation not permitted

**Comment by ukanth** [comment] 2018-09-10 15:01
This usually happens when already the other instance of nflog running.

**Comment by ukanth** [comment] 2021-03-13 09:28
Duplicate of #1002

**Closed as completed by ukanth** 2021-03-13 09:28 UTC
Labels: Bug, Low
