### ISSUE TITLE
menu language

### ISSUE THREAD

**Issue by jonathanhzs** [ukanth/afwall#1089] opened 2020-02-20 00:37 UTC
In your source code, the Chinese language name is zh and zh-rCN.
 But the corresponding statement in the configuration file is zh-cn, which causes the language display to be incomplete after the software is set.

**Comment by jonathanhzs** [comment] 2020-02-20 00:40
zh-cn&zh-tw

**Comment by jonathanhzs** [comment] 2020-02-20 23:53
In your source code, the Chinese language name is zh and zh-rCN.
 But the corresponding statement in the configuration file is zh-cn, which causes the language display to be incomplete after the software is set.

**Comment by ukanth** [comment] 2020-09-01 03:38
It does point to the right resource in strings.xml 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/165996/91792240-b48ed180-ec32-11ea-907a-448e600f412f.png">

**Comment by ukanth** [comment] 2021-03-07 11:21
Duplicate of #1143

**Closed as completed by ukanth** 2021-03-07 11:21 UTC
