### ISSUE TITLE
Unknown process in the log

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#835] opened 2018-05-31 18:47 UTC
Hi

I have been getting this "Unknown(1000)" process in the log (paid user here) since the last update. I do not remember this unknown thing before, and I cant see some of my individual app logs, I believe they are bundloed in this uknown process for a while.
'
I am using Lollipop 5.1 with Afwall 2.9.9

thanks

**Comment by gerroon** [comment] 2018-06-25 15:56
Any ideas why I have theis new "Unknown" process started showing up? I doubt it is a single process, Many apps are bunbled in this thing for sme reason

**Comment by JGKle** [comment] 2018-07-05 19:02
Same issue/question: the highest number of denies in my logs are "Unknown(1000)." Galaxy S9 on Android Oreo (8.0).

**Comment by gerroon** [comment] 2018-07-05 19:39
Yeah this unknown process is quite new. I hope the devs chime in.

**Comment by JGKle** [comment] 2018-07-05 19:44
Just from the icon, it looks like it could be something related to Bixby...?

**Comment by gerroon** [comment] 2018-07-05 20:06
I do not know what Bixby is, never installed such thing, it is nto listed in Afwall, nor Unknown process was an issue until recent updates

**Comment by JGKle** [comment] 2018-07-05 20:08
Bixby is built into all Samsung phones - it's their stupid virtual assistant. Always there, not something you would've installed. On my device the Unknown Process icon appears like the Bixby icon (though that could just be the app misreading something).

**Comment by gerroon** [comment] 2018-07-05 20:09
metal450, sure my phone is a Note 2014, not sure if they had that bixby thing then. I also frooze most of Samsung crap. But like I said, unknown thing is new as far as I can tell and it takes massive portions of the log. Because of this unknown process, my log file grows to hundreds of megs.

**Comment by gerroon** [comment] 2018-07-05 20:13
Btw the icon for unknwon process in the log on my phone just looks like a regular android icon with that green dude with 2 antennas.

**Comment by gerroon** [comment] 2018-07-15 15:02
I upgraded to Lineageos 14 from 5.1 and I still have this unknow process thing, so this is not an OS related issue. 

@ukanth please join the conversation and tell us what your take is on it

**Comment by ukanth** [comment] 2018-07-15 15:34
it's a bug. I thought I fixed it. will look into it.

**Comment by gerroon** [comment] 2018-07-15 16:25
@ukanth 

thanks, can you also make sure that the logs do not get to hundreds of megabytes ? :)

**Comment by ukanth** [comment] 2018-07-16 03:48
in the new log it does purge after certain limit. don't remember it. are you using old log ?

**Comment by gerroon** [comment] 2018-07-16 04:10
I am using the donation version. Not sure if it is the old or new. But my logs get to 180mb+ due to this unknown(1000) logs especially. I have to regularly remember to delete the log file because I cant even open the log window in Afwall, well due to the huge file size I guess.

**Comment by vzool** [comment] 2018-07-16 08:38
Same issue here at OnePlus Oreo 8.0.0 AFWall+ (v2.9.9).

**Comment by kekukui** [comment] 2018-08-16 13:14
**I'm seeing this on Android 7.0 for Samsung**

![afwall pid 1000 alert](https://user-images.githubusercontent.com/20834957/44209359-39cce980-a131-11e8-88ff-655a9054c4a6.png)

1000 seems to be a sticky/reserved PID for some kind of system service which does a lot more than it should, so you have to allow the bad with the good.  A few apps which depend on Google Play Services may require (or demand) it, and its always connecting to some Google server -- possibly more than necessary (which is typical for Google apps & services.)

I also noticed how the icon changes in various AFwall displays according to which app is currently using the service.  That may be a key to gaining more control and visibility over this tarball service.

![pid 1000 description a](https://user-images.githubusercontent.com/20834957/44209436-7ac4fe00-a131-11e8-9efe-a096d196021c.png)

![pid 1000 icon - v2](https://user-images.githubusercontent.com/20834957/44211430-f37a8900-a136-11e8-9c95-80fc044362ff.png)

![pid 1000 icon - v1a](https://user-images.githubusercontent.com/20834957/44211333-b7dfbf00-a136-11e8-907e-0f0a79824bc2.png)

![pid 1000 connections](https://user-images.githubusercontent.com/20834957/44210754-5a973e00-a135-11e8-8b97-f29840d1b7d0.png)

**Related topics**

https://github.com/ukanth/afwall/issues/518#issuecomment-277996449
How to disable captive portal detection
https://android.stackexchange.com/questions/100657/how-to-disable-captive-portal-detection-how-to-remove-exclamation-mark-on-wi-fi

**Comment by ukanth** [comment] 2021-09-24 01:52
Duplicate of  #1232

**Closed as completed by ukanth** 2021-09-24 01:52 UTC
Labels: Review
