### ISSUE TITLE
Restrict multi-user mode configuration to owner account

### ISSUE THREAD

**Issue by wallclimber** [ukanth/afwall#259] opened 2014-02-26 13:21 UTC
I can't get multi-user mode to work reliably on my tablet with a custom Cyanogenmod 10.2 ROM. I suspect it's because of conflicting options or iptable rules when two instances of afwall are run by the owner and another user (u10, u11, etc).

I believe the problem can be fixed by changes to the afwall UI that will either (1) restrict iptables administration to the owner; or (2) allow other users to configure only User apps enabled for their accounts (no Core or System apps).

Under my first suggestion (1), only the owner account can enable, disable or otherwise configure afwall. When started by another user, afwall can display a warning like "Switch to owner account to configure afwall".

Only the owner will be allowed to whitelist or blacklist apps, including apps enabled for other users. This will make the list of installed apps longer for systems with multiple users. However, a filter can be added to show or hide apps installed for other users. Such apps can also be "tagged" by user name. For example, the Firefox app installed for user Alice (user 10) can be shown in the list of installed apps as "Firefox (Alice)" or "Firefox (u10)".

Alternatively, afwall can provide a separate list of User apps for each user. Apps installed for users other than the owner account will be grouped together in a separate window or tab with the corresponding user label (Alice's apps will appear under the Alice tab, Bob's apps under the Bob tab, etc).

**Comment by ukanth** [comment] 2016-08-03 06:01
Duplicate of #271

**Closed by ukanth** 2016-08-03 06:01 UTC
Labels: Bug
