### ISSUE TITLE
danger: afwall free and afwall+ after version afwall 2.9.1 to version 2.9.5 there is data leaks.

### ISSUE THREAD

**Issue by peturbg** [ukanth/afwall#726] opened 2017-07-21 01:58 UTC
i will paste that i write to other user. but first i will include in this message. peoples do not install after version 2.9.1 there is data leaks. how i say this data leaks continue after version 2.9.1. if you have afwall+ 2.9.1 it will block what is blocked, but in version 2.9.1 it dont block ipv6. you need yo disable ipv6, but in samsung s7 if you disable ipv6 after disconnect of wifi it will again has ipv6 ao you need again yo disable everytime wifi, reboot mobile, airplane mode and etc. i cant imagine why ukanth ia selling his ass to make hiw wonderfull program send data leaks and help od the elite and governments spy on you.
hi guys.

now this is serrious problem for the peoples and im gonna ask the developer ukanth why you sell your ass to the elite and governments. ukanth your afwall+ was great before 2.9.1 after that to 2.9.5 include the new version DATA LEAKS. i install the latest include i install veraon 2.9.4 and it too data leaks. so when i install 2.9.5 or was leaked. so after i return to 2.9.1 ALL WORKS GREAT. why ukanth the firat day the problem start i wait to see if you are gonna repair the problem AND YOU ukanth DONT WANT TO REPAIR THE PROBLEM. YES im the person who wrote you email and you disnt want repair the DATA LEAKS. so why i nees to pay for a program that is like microsoft that DATA LEAKS all data illegaly or legally. afwall+ is to block not to data leaks. HEY GUYS return to 2.9.1 and you are gonna see the afwall+ works perfectly. from two or three version of afwall+ it start data leaks include now i have fears to install if afwall+ has new version. ukanth tell of the peoples if you want more money and stop SELL you ass to tge elite ans governments peoples. for this peoples who love afwall+ and didnt buy the program. please dont buy the program becouse after version 2.9.1 to version 2.9.5 afwall+ is DATA LEAKS, no mather what you do afwall will leaks include if you turn log on it will not log anything. im with super su 2.7.9 sr3 on nougat galaxy s7. so guys dont buy afwall+ version 2.9.5 becouse it is like you dont nothing. ukanth bratushka if i remember corrwctly you are from ukraine stop selling your ass and if someone put pressure on you comment it here and make youtube, if you tell the true only the peoples will help you, the elite and governments are only killing peoples dont belive them. ukanth this issue is high, it continue how i say more than one time in this message fix it and make too block ipv6, becouse in versio 2.9.1 blockipv6 dont work and some program google play conctact on ipv6.

**Comment by ukanth** [comment] 2017-07-21 09:58
Duplicate of #709

**Closed by ukanth** 2017-07-21 09:58 UTC
