### ISSUE TITLE
[Request] Reapply current profile via Tasker

### ISSUE THREAD

**Issue by an0n981** [ukanth/afwall#292] opened 2014-07-20 15:21 UTC
Currently it is only possible to reapply a predefined profile via Tasker. There are circumstances where the current profile (whichever is active) needs to be reapplied.
Therefore a request to either:
1. Ability to query the currently active profile
Or
2. Plugin option 'reapply current profile'

**Comment by ukanth** [comment] 2021-03-12 18:00
Duplicate of #1159. Since it's too old, merging with the latest one.

**Closed by ukanth** 2021-03-12 18:00 UTC
Labels: Feature
