### ISSUE TITLE
AFWall 2.0.0-Beta-2 GUI Crash on maguro w/ 5.1.1

### ISSUE THREAD

**Issue by wbedard** [ukanth/afwall#399] opened 2015-08-03 21:20 UTC
Hey Ukanth,

Unless the brief logcat provided at the link below highlights something obvious to you, please feel free to rate this as low confidence/priority for now.  I just updated all my devices to the new beta and one of them has the GUI force-closing, though the background process still shows as running in the notification tray.  I won't have any time to debug this on the device until the later part of next week.  That said, the crash occurs on the most "non-stock" device I have (Galaxy Nexus/maguro, Android 5.1.1, rooted, XPosed w/ several modules, SELinux in enforcing, etc).  That said, the GUI runs fine on a very similarly configured Nexus 5.  Obviously there are a lot of things I can dial back a bit to see if they are the cause of the crash.  If the logcat doesn't help you figure it out on your own, expect that I will follow-up with add'l testing results next week.  

http://pastebin.com/cH7XHQmC

**Comment by CHEF-KOCH** [comment] 2015-08-03 21:37
Mostly a duplicate of #396, please also remember to write down what beta you exactly use, but from the context I think it's B-2. :smile:

**Comment by wbedard** [comment] 2015-08-03 21:41
You are so right!  I was in such a hurry that I didn't even take time to review the outstanding issues.  Thanks for noticing for me!

**Comment by CHEF-KOCH** [comment] 2015-08-03 21:51
You're welcome.

**Closed** 2015-09-09 10:16 UTC
Labels: Bug, Duplicate
