### ISSUE TITLE
Duplicate items on apps list

### ISSUE THREAD

**Issue by runo280** [ukanth/afwall#881] opened 2018-10-14 15:48 UTC
Some times when I open the app it will shows the apps list like this, pull to refresh or re-opening the app will fix it but it's a little bit annoying. I faced it on latest stable (2.9.9) and beta version (3.0.0).
I'm on Lineage 14.1 (Latest Nightly) for Honor 5x.

![screenshot_20181014-185925](https://user-images.githubusercontent.com/13608702/46918984-5b3d3b00-cfe5-11e8-8133-4f8cd2fe7b7b.png)

**Comment by ukanth** [comment] 2018-10-15 02:11
Duplicate of #871

**Closed as completed by ukanth** 2018-10-15 02:11 UTC
