### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by IronGibbet** [ukanth/afwall#1296] opened 2022-07-08 19:25 UTC
**Is your feature request related to a problem? Please describe.**
Unknown apps show up in the log.

**Describe the solution you'd like**
If an app is shown in the log that was blocked but is not shown in the app list (system app enabled)
permanently make it controllable through the GUI.

Thanks in advance.

Best regards 
IG

**Comment by ukanth** [comment] 2022-07-09 02:39
Duplicate of #1250

**Closed as completed by ukanth** 2022-07-09 02:39 UTC
