### ISSUE TITLE
Problem with Private DNS

### ISSUE THREAD

**Issue by jw243** [ukanth/afwall#1022] opened 2019-10-06 23:15 UTC
Moto X4
LineageOS 16 with microG (version 2019/10/03)
AFWall 3.1.0
fdns1.dismail.de

When AFWall, Private DNS and an activated SIM card come together in my smartphone, the system freezes shortly after bootup and starts to reboot.

The system works when only two of the three conditions are present, i.e.:
- without a SIM card (without mobile data)
- with private dns disabled
- without AFWall

Will there be an update of AFWall soon that will address the private dns issue?

**Comment by kamilr** [comment] 2019-10-08 07:47
Sgs s9
LineageOS 16 with microG (version 0.2.8.17785-mapbox - 03.07.2019)
AFWall 3.1.0
fdns1.dismail.de (80.241.218.68)

Works fine.

**Comment by jw243** [comment] 2019-10-08 12:10
Did you use Private DNS (Settings > Network & Internet > Advanced > Private DNS)?
And did it all work when you were on mobile data?

Your Lineage version seems quite "old". Maybe my problems are caused by the Lineage update, as recent nightlies seem to cause other problems, too, such as reboot when idle (which is supposed to be fixed) and bootloops when rebooting the phone?

**Comment by jw243** [comment] 2019-10-08 12:16
#985  
Is Private DNS in combination with AFWall still a problem, especially on mobile data connections?
Is there a solution using custom scripts?
Will this problem, if it still exists, be addressed in the next update of AFWall?

**Comment by kamilr** [comment] 2019-10-16 13:05
I have no problems with wifi or mobile data in combination of any DNS option in API 28 (private, custom). You can try with solution of "settings set xyz" via shell like it was in API 27, but I'm not sure about it. 
For me custom scripts doesn't work. But it's another problem of mine configuration.

**Comment by kamilr** [comment] 2019-10-16 13:08
I using the very latest stable built from miroG f-droid repository. LOS, june bulid, of synt4x93.

**Comment by MountainX** [comment] 2019-11-27 18:22
I am trying to reproduce this. However, when I enable Private DNS with AFWall+ also enabled, my browser cannot resolve any names. Which setting in AFWall+ needs to be checked to allow Private DNS? All that I tried had no efffect. With my current settings Private DNS works only when AFWall+ rules are disabled, so I must be missing a rule that I need to enable. Once I resolve that, I will try to reproduce this issue and give my feedback here.

EDIT: I found more info here: https://github.com/ukanth/afwall/issues/985

**Comment by CHEF-KOCH** [comment] 2019-12-02 11:38
AFWall+doesn't cause any "sim card freezes", nor does have AFWall+ permissions to interfere with a SIM card.

> Is Private DNS in combination with AFWall still a problem, especially on mobile data connections?

Android P is the problem and known to be flawed. This is not a surprise, most features which are getting firstly introduced are full of bugs, this got fixed in Android 10. See the official FAQ for more information regarding Private DNS (point 64). AFWall+ does not open up 853, so you need to do this manually via script. 

DOH and DoT are controversial and I'm against those systems. 

> Which setting in AFWall+ needs to be checked to allow Private DNS?

None, it's not included which means the whole thing is a feature request. Again [I see more problems with DOH and DoT in his current form](https://github.com/CHEF-KOCH/FFCK/issues/7). 


The thread is basically a duplicate of #985 and should be closed.

**Comment by ukanth** [comment] 2021-03-07 09:11
Duplicate of #1176

**Closed as completed by ukanth** 2021-03-07 09:11 UTC
