### ISSUE TITLE
[ISSUE] AFWall+ seems to be highly unreliable and not very forthcoming with details about problems

### ISSUE THREAD

**Issue by lemmy04** [ukanth/afwall#1237] opened 2021-09-14 09:55 UTC
**Describe the bug**

Applying the firewall rules fails more often than it succeeds, with no detail about what exactly went wrong ("Unknown error while applying the firewall rules")

**Smartphone (please complete the following information):**
 - Device: Samsung S8+, Samsung Tab S5e, Samsung S20FE 2021
 - Android OS: Samsung branded Android 8, 10, 11

**Additional context**
seeing how AFwall reapplies the rules all the time (when connectivity changes) it basically is breaking connectivity most of the time.

Almost every time i want to use my phone after moving around in my home (i.e. getting to a different wlan AP) I have to manually disable the firewall, flush the rules, and enable the firewall again.

**Comment by nocturn9x** [comment] 2021-09-15 10:58
Having the same issue on my Xiaomi Mi 11i running MIUI 12.5 Global and Magisk v23. Sometimes the app just fails and I have to reboot to fix it

**Comment by lemmy04** [comment] 2021-09-15 11:14
I'm thinking that it has to do with the number of applications: i'm in the process of setting up a new phone right now and first AFwall would work just fine, but somewhere around 500+ apps it started to fail more and more often.

**Comment by ukanth** [comment] 2021-09-15 15:43
Can you try this version and see if this helps ? 

https://www.dropbox.com/s/f1fekfxpqmvw2mg/AFWall%2B_3.5.3_BETA1.apk?dl=0

**Comment by DanielRieken** [comment] 2021-09-17 06:29
@lemmy04 could you also upload the logfiles, as soon as you get an error-message?
"Show rules" -> "Export to storage" (IPv4rules.log) -> "Switch IPv6 rules" -> "Export to storage" (IPv6rules.log)
In german language:
"Regeln anzeigen" -> "Regeln exportieren" -> "IPv6-Regeln einschalten" (schlechte Übersetzung) -> nochmal "Regeln exportieren"

**Comment by idovitz** [comment] 2021-09-17 06:56
Had trouble with disconnecting wifi for months. Suspected first openwrt, then android, but didn't find proof. Got this afwall apply errors. Used Netguard instead of afwall for a week and no disconnects anymore. Now using this beta afwall 3.5.3, seems stable again.

**Comment by DanielRieken** [comment] 2021-09-17 07:04
@idovitz you did not found this before? https://github.com/ukanth/afwall/issues/1206

**Comment by idovitz** [comment] 2021-09-17 09:33
Nope sorry, and disabling ipv6 didn't work for me. (and i like my dual stack ipv4/6 setup ;) )

**Comment by ukanth** [comment] 2021-09-20 06:09
duplicate of #1206

**Closed as completed by ukanth** 2021-09-20 06:09 UTC
Labels: Review
