### ISSUE TITLE
Connection confirm dialog - feature proposal

### ISSUE THREAD

**Issue by smarek** [ukanth/afwall#269] opened 2014-04-06 22:38 UTC
Hi,

thanks for great project.
Anyway, I'd be willing to implement this, just wanted to start wider discussion.

I really like Little Snitch user-flow feature, which creates rules per application (by it's path), user id (by process identifier) and per connection (each time application requests to open connection, it will lookup in white/black-list, and without rule applicable to current situation, will throw user dialog to confirm what to do.

To illustrate the situation, i include few screenshots of LS3

![Standard dialog](https://cloud.githubusercontent.com/assets/384824/2626617/bbb7d03e-bdda-11e3-8299-a4eb9cea63ae.png)
![Time based rules](https://cloud.githubusercontent.com/assets/384824/2626616/bbb6a498-bdda-11e3-9848-6755da0c2b4f.png)
![Domain / Port based rules](https://cloud.githubusercontent.com/assets/384824/2626615/bbb613ac-bdda-11e3-9b64-b21ce0e7665f.png)

It would be really handy to get confirmation dialog on each connection, where rules are made per application uid/guid

Rules (per app)
  - URL + PORT
  - DOMAIN + PORT
  - PORT (any url/domain)
  - URL (any port)
  - DOMAIN (any port)
  - Anything (any domain/url/port, the app is fully trusted then)

Time based
  - Once
  - Time interval (5,10,15,30,60 minutes)
  - Until process is killed (if possible)
  - Until device is restarted
  - Forever

Application should then provide permanent service notification, where the user could quickly access list of allowed/denied connections (eg. over last 15 minutes) and rules editor, where you could review and debug requests made by application (some short backlog) and see what rules are denying those requests, to easily fix wrongly set rules.

Possibly could be extended by accepting URL patterns similar to AdAway/AdBlock,
white/black-listing allowed underlying network type (cellular,wireless,tethered,vpn,...) and (which is really crazy detailed option) for HTTP requests types (such as GET,PUT,POST,DELETE,UPDATE,...)

So if you please could discuss over this proposal, what would fit your idea, as I said, I'm willing to implement this in open-source, because it would be really good privacy feature, which could possibly replace various adblock solutions and if divided into profiles (home,work,traveling) and user account specific (for multi-user android devices), make really solid user-friendly firewalling solution.

**Comment by rancidfrog** [comment] 2015-02-25 15:36
It would be great to have a prompt for only a certain white-listed apps, (I do not think it necessary to have it per-connection, though), to temporarily enable internet access for X amount of time.

I did not see this issue when I searched.

**Comment by CHEF-KOCH** [comment] 2015-02-26 06:08
Why you ask for something which was already described in the first post? Look -> **Time based**

No, it's not possible to implement proper for all, so please give up on this. It's already almost one year old without anything and I saw other 5 years old threads with exactly the same idea.

There are already several "implementations" (_-m time_ /timestart/timestop) patches for a time module in standard kernels, but you need to patch/compile it yourself. Read, [here](http://www.bufferbloat.net/issues/95), [here](http://www.cyberciti.biz/tips/iptables-for-restricting-access-by-time-of-day.html) and I answered already [here](http://www.linuxquestions.org/questions/linux-security-4/iptables-restrict-internet-access-based-on-time-of-day-and-mac-address-787456/). - [Example](http://whirlysworld.blogspot.de/2013/08/blocking-internet-at-specific-times.html). And of course it's already well documented over the official [iptables man page](http://ipset.netfilter.org/iptables.man.html).

**Comment by ukanth** [comment] 2016-08-03 06:21
Duplicate of #10

**Closed by ukanth** 2016-08-03 06:21 UTC
Labels: Feature

**Comment by vzool** [comment] 2017-01-21 18:31
Maybe it looks like it's so long list of requirements, but I feel differently.

> **With root we become gods.**

I think that if we just start with a simple dialog of confirmation derived from [LogService](https://github.com/ukanth/afwall/blob/stable/aFWall/src/main/java/dev/ukanth/ufirewall/log/LogService.java) as @ukanth suggested, and the dialog offer these options:

- Block.
- Allow once.
- Allow forever.

After that we can enhance it and expand it with and while Android been developing and involve closer to proposal bone, I guess that we are not so far. I prefer [xPrivacy](https://github.com/M66B/XPrivacy) way of dialog, it may serve us well.
It behaves so closely and even better to what SuperSu offer.

Thanks

![alt tag](https://github.com/M66B/XPrivacy/raw/master/screenshots/on-demand-dialogue.png)
