### ISSUE TITLE
Mobile data connection icon dissappears unless a particular item containing many subcomponents is allowed.

### ISSUE THREAD

**Issue by irontechmonkey** [ukanth/afwall#441] opened 2015-10-05 06:08 UTC
Mobile data connection icon dissappears unless a particular item containing many subcomponents is allowed.. That item is

"Setup Wizard, Android System, CyanogenMod System, MotoDoze, Settings Storage, Input Devices, Phone, Key Chain, CM Settings Storage, Settings, FM Radio, Fused Location, Dev Tools"

![screenshot_2015-10-05-02-00-33](https://cloud.githubusercontent.com/assets/14972114/10273928/aabe0508-6b05-11e5-9359-ebb0c14b58d1.png)

NOTE: CANNOT ATTACH TEXT FILES - HAD TO RENAME LOG FILES WITH PNG EXTENSION.  RENAME ATTACHED LOG FILES WITH TXT EXTENSION

Log files LOG AFWallX01-2015-10-05-01-50-37 and LOG AFWallX01-iptables are from a mobile data connection made under whitelist mode with all items un-checked. Mobile data connection icon briefly appears then disappears. 

![log afwallx01-2015-10-05-01-50-37](https://cloud.githubusercontent.com/assets/14972114/10274085/a5530bac-6b07-11e5-9887-44b60ffaa6c4.png)

![log afwallx01-iptables](https://cloud.githubusercontent.com/assets/14972114/10274086/a89c375c-6b07-11e5-9889-fc2c929b0bf7.png)

Log file AFWallX02-2015-10-05-01-57-48 is from a a mobile data connection under whitelist with only the aforementioned mega-item checked. In this case the mobile data icon displays properly.

![log afwallx02-2015-10-05-01-57-48](https://cloud.githubusercontent.com/assets/14972114/10274128/232b8004-6b08-11e5-9ce4-e2a25494a80f.png)

RENAME ATTATCHED LOG FILES WITH TXT EXTENTION

**Comment by an0n981** [comment] 2015-10-05 10:26
Try entering the following command in terminal emulator

su -c "settings put global captive_portal_detection_enabled 0"

**Comment by CHEF-KOCH** [comment] 2015-10-05 16:28
On newer OS e.g. AOSP 5.5.5 (alias 5.1.1. r18 or higher) this will no longer work via adb (you can use this there but it has no effect). The Capital Login apk was now isolated from the OS, so if you don't like or have any problems you can just freeze/uninstall the app.

**Comment by irontechmonkey** [comment] 2015-10-05 19:12
When this issue was first created in github it was accidentally described as a failure to connect to mobile data when a certain item was not enabled in AFwall. That was incorrect. The issue is actually that the Mobile data icon is not visible  when that item is not enabled.

**Comment by irontechmonkey** [comment] 2015-10-05 19:22
@CHEF-KOCH, Thanks. You speak from a more informed development point of view than I, however from a logical point of view; As to Google Play Services controlling that icon,  The icon work properly in lean ROM without Gapps so I don't know if that holds true. Also If I remember correctly, pre-beta Afwall did not have this issue on same ROM. One fact remains clear - That something that hides an icon that indicates connectivity state, undermines safety provided by Firewall.

**Comment by irontechmonkey** [comment] 2015-10-05 19:23
@an0n981 Thanks. Is this suggestion to address the issue as I first misstated it [cannot establish mobile data connection] or to address the issue as it actually is [mobile data icon not visible]?

**Comment by CHEF-KOCH** [comment] 2015-10-05 20:28
> Also If I remember correctly, pre-beta Afwall did not have this issue on same ROM.
This could be due the fact some stuff was changed on AFWall+, was an bug that doesn't applied iptables. 


> That something that hides an icon that indicates connectivity state, undermines safety provided by Firewall. 

AFWall+ doesn't filter gsm traffic so you normally can set whatever you want it will not be blocked. It only affects apps that use internet permissions. 


> The icon work properly in lean ROM without Gapps so I don't know if that holds true.

Would be interesting to know, which rom doesn't come with gapps (not even with play services) because without it it would break almost everything since most external apps are depending on this, e.g. for ads services, nearby, proxy's and such. But it's maybe within the settings.apk, maybe a special case but difficult to say without any additional info.

**Comment by irontechmonkey** [comment] 2015-10-05 20:52
@CHEF-KOCH Thanks again. CM does not come with Gapps [was that a trick question?;)] although it certainly contains Google components. Perhaps you meant google services instead of entire Gapps package? Also, I'm not sure if my report is being properly understood. This seems to be a GUI issue and not an issue of what it being allowed through firewall.

When a certain item in Firewall is not selected for whitelist  the status bar icon which indicates mobile data connection is hidden even though mobile data is connected. If that certain item is selected in Firewall the icon is visible [circled in red in attached picture].

![afwallstatusbar](https://cloud.githubusercontent.com/assets/14972114/10293244/797e4cd8-6b81-11e5-81a6-5731b1df2a6b.png)

Clearly Afwall is capable of not causing the mobile data connection icon to disappear, as is the case most of the time, and as should be the case all the time. Simply put a Firewall undermines it's self if it obscures the data connection state from the user. As there are other issues with Afwall in re the GUI [using tasker to change profiles not reflecting in notification shade items] I'm hoping that it is an addressable GUI issue.

**Comment by CHEF-KOCH** [comment] 2015-10-05 21:46
Well, my comment was on the ! icon which is visible on your first screenshot, that definitely comes from the services intent or as said if not present from the settings/system. 

The last screenshot is more detailed, because it seems to show an glitch or bug or whatever you want to call it. I get this sometimes if I not re-flashed my modem or forget to wipe xyz z after an rom upgrade (dirty flash called). 

Yeah, my main intent was that I only saw very lass people with 'gapps' .. speaking about services only here, installed, as I said it would break a lot of stuff and you will get a lot of warnings/errors on certain apps. 

> Clearly Afwall is capable of not causing the mobile data connection icon to disappear, as is the case most of the time, and as should be the case all the time.

If that's true then we need to close it, but before we do this it would be worth to ask in the ROM thread for it. Maybe this glitch or whatever we want to call this is 'known' issue or can be fixed with the next build. 

So we need some investigation on this.

**Comment by irontechmonkey** [comment] 2015-10-05 21:58
@ CHEF-KOCH. All good points and thanks for the clarification. As I retested I  realized you were referencing the exclamation point (which is present whether or not mobile data is connected and, afik, is an indication of background data status*).

I am active in multiple related ROM threads at XDA and elsewhere and the Afwall thread at XDA. I've seen nothing about this but will keep looking. Unfortunately the thread and Dev for my [low end and last in line] device is young and has not attracted much Dev. We've got official CM nighlys but have not reached first snapshot so cannot file jira bugs. If and when we get our OTA from L5.0.x to L5.1.x things should start moving.

As a general observation: Data and wifi toggling has gotten more cumbersome in general and particularly so in CM. Perhaps that is part of the problem. If you can think of any other helpful details I could provide do tell.

Thanks again!
- [EDIT] Correction. That exclamation point indicates [as you seemed to already know] status of connections to Google services, which does make it an incidental but not absolute indicator of background data state as it is not visible in Mobile data connection if background data is not enabled [because there is no connection to Google services?].

**Comment by CHEF-KOCH** [comment] 2015-10-06 13:23
What also comes to my mind (sorry I'm to lazy today to search) that the experimental option 'blocks' the 'indicator' we've talked about. Someone reported that the 'startup data leak' fix breaks android 5x from connect to anything (you'll properly see such ! or any other icon too if it was enabled). 

> because there is no connection to Google services?

If the hartbeat that is necessary to monitor/check connection was disabled/blocked it also shows 'blocked' icons in the status bar. Maybe this is the entire magic behind it.

**Comment by cb474** [comment] 2015-11-04 03:18
I am also having this problem. If I don't whitelist "Setup Wizard, Android System, Settings Storage, Input Devices, Phone, Key Chain, Settings, Fused Location, Dev Tools" I see the exclamation point on the cell signal icon instead of "H" or "LTE." This is with CM 12.1 (most recent snapshot) on a Nexus 4 and OpenGapps. But mobile data is working fine.

**Comment by CHEF-KOCH** [comment] 2015-11-04 09:30
We not support etas official. So you own you own. 

The icon dissapear as I said if the heartbeat couldn't be proper send because it is blocked. So, tis isn't a bug at all. But it's maybe something for CM team to look at, in fact even if they change it, how long it would take until the next report it dissapear because he blocked the changed stuff. Overall I see no point, add an exclusion only for this is not necessary since mobile data anyway will work and it's just nothing but a visual glitch on a static icon.

**Comment by irontechmonkey** [comment] 2015-11-04 17:34
I think we might be focusing too much on the exclamation point icon and ignoring some factual details and top-down logic that indicate that this is indeed an Afwall issue:
- Only occurs with AFwall's newer 2.xversion. 
- Did not occur in the older version of Afwall across multiple ROMs and devices.
- Occurs in CM AND stock Motorola (Moto E) ROMS.
- It is only the network type sub-icon that is affected. The exclamation point icon is not affected.
- The catchall item in the Afwall list that is blocking the icon seems almost redundant and there seem to be other individual items in the Afwall list that handle the same things.
- Having no network indicator is not an option and works directly against the idea of firewall protection. 

I have a workaround by enabling mobile data programatically and creating a notification icon for it with tasker but this sort of thing  is a deal-breaker for a firewall app and it is clearly not CM specific.

**Comment by SafwatHalaby** [comment] 2015-11-04 20:13
Can anyone provide some info about that app? What does it do? Unblocking it resolves the icon issues. Is it safe to unblock it?

**Comment by SafwatHalaby** [comment] 2015-11-04 20:20
By the way, I don't have Google Apps or Google Services or any open source Gapps alternative, and I'm also seeing this. Whitelisting the app mentioned above resolves it.

**Comment by irontechmonkey** [comment] 2015-11-04 22:59
@SafwatHalaby, It is not an app but rather a bunch of system components (visible in the image attached to OP in this thread). Many people use firewalls to block things just those sorts of system components, and it undermines the use of firewall to open up all those things just to restore the icon.

**Comment by SafwatHalaby** [comment] 2015-11-05 07:19
@irontechmonkey In practice, do any of these system components access the internet or accept incoming connections?

**Comment by irontechmonkey** [comment] 2015-11-05 18:05
@SafwatHalaby Good question. I'm not sure but I'm not leaving the door unlocked to find out. IMO no items should have to be blocked or unblocked just to control a graphic indicator.

**Comment by lusagad** [comment] 2016-05-08 13:07
Hi! Another one w/same issue using a H-850 LG. Have to deactivate when I boot up the phone or change mobile data connecc. When AF+ is off, and the icon's back, restart the firewall. That's my "solution"

**Comment by irontechmonkey** [comment] 2016-05-08 18:42
@lusagad ,[EDIT] I mis-stated earlier about this being fixed by an update. It was fixed by this command or a variation thereof:

su -c settings put global captive_portal_detection_enabled 0 

Shared here: http://forum.xda-developers.com/showpost.php?p=65652627&postcount=2973

**Closed as completed** 2017-02-24 04:09 UTC

**Comment by ilf** [comment] 2017-06-13 21:36
I have this again on Android 7.1.2, but even with "captive_portal_detection_enabled 0" it does not go away. Is there a new workaround?

**Comment by Micha-Btz** [comment] 2017-06-14 04:43
please try settings put global captive_portal_mode 0 this has changed in framework for nougat

**Comment by ukanth** [comment] 2017-06-14 04:50
@Micha-Btz  Thanks for the details. I can confirm that it's changed in 7.x

https://android.googlesource.com/platform/frameworks/base/+/android-7.1.2_r5/core/java/android/provider/Settings.java#8027

for Nougat 
`su -c settings put global captive_portal_mode 0`

for other versions
`su -c settings put global captive_portal_detection_enabled 0`

**Comment by ilf** [comment] 2017-06-27 20:55
@Micha-Btz Thanks, that did it.

Since afwall has root, couldn't this be an afwall setting?

**Comment by Micha-Btz** [comment] 2017-06-28 05:10
@ilf maybe @ukanth can implement this but you can also create a custom script for afwall
with:

> settings put global captive_portal_detection_enabled 0
> settings put global captive_portal_server localhost
> settings put global captive_portal_mode 0
