### ISSUE TITLE
3.5.0 error applying rules

### ISSUE THREAD

**Issue by ngrigoriev** [ukanth/afwall#1206] opened 2021-04-26 02:38 UTC
**Describe the bug**
After upgrading to 3.5.0 it seems that I can no longer apply the rules. Or I should say "almost" because it works probably 1/30.

**Firewall Logs**
Emailed the complete log to afwall-report@googlegroups.com

The log is full of the similar lines:

```
====== 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/iptables -A afwall-3g-home -m owner --uid-owner 10268 -j RETURN' exited with status 4, retrying (attempt 1/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 1/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 2/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 3/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 4/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 5/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 6/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 7/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 8/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 9/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4, retrying (attempt 10/10) 22:18:33 command '/data/user/0/dev.ukanth.ufirewall/app_bin/ip6tables -A afwall-3g-home -m owner --uid-owner 10257 -j RETURN' exited with status 4 Output: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
```

**Smartphone (please complete the following information):**
 - Device: Nokia 8.3 5G
 - Android OS: stock Android 11 (00WW_2_200)

**Additional context**

It appears like a plain race condition. I have found that disabling IPv6 support appears to fix the problem. And it appears the app tries to apply both IPv4 and IPv6 rules concurrently. Which probably explains the message about "another app holding xtables lock", the reason why the app appears to retry the commands and also explains why sometimes it works.

Maybe it should simply apply the rules sequentially?

**Comment by ukanth** [comment] 2021-04-26 02:45
Do you have Private DNS enabled or any other firewall installed ?

**Comment by ngrigoriev** [comment] 2021-04-26 03:00
Nope. And the previous version of AFWall+ was working perfectly. And I have not applied any updates (except regular app updates) in between. Does AWFall+ run iptables commands in parallel for IPv6 and IPv4? It is probably fighting with itself?

**Comment by ngrigoriev** [comment] 2021-04-26 03:06
By the way, with IPv6 disabled, it works correctly with both system and bundled iptables binary, I see no differences. Tried one more time - with IPv6 enabled it fails after a few dozens of rules. Without IPv6 enabled it works 100% and I tested the firewall functionality with the browser app, works as expected.

**Comment by ukanth** [comment] 2021-04-26 04:22
No, there is no race condition between ipv4 and v6.  Please provide logcat and firewall rules exported to see more details

**Comment by ngrigoriev** [comment] 2021-04-26 13:00
[afwall-backup-all-2021-04-26-08-54-33.json.gz](https://github.com/ukanth/afwall/files/6377169/afwall-backup-all-2021-04-26-08-54-33.json.gz)
[IPv4rules-ipv4only.log.gz](https://github.com/ukanth/afwall/files/6377171/IPv4rules-ipv4only.log.gz)
[IPv4rules-ipv4and6.log.gz](https://github.com/ukanth/afwall/files/6377172/IPv4rules-ipv4and6.log.gz)

Attached the current rules and two exported logs. If IPv4 and IPv6 are enabled, "Apply rules" operation always fails. If I disable IPv6, this operation always succeeds.

**Comment by pizzadude** [comment] 2021-04-27 18:10
I have the same issue. Moto Z2 Play, Android Pie. Disabling ipv6 solves the issue.

**Comment by est61** [comment] 2021-05-03 01:11
Same issue here. v3.4.0 has been working perfectly since 12 Feb 2020.
Today i decided to upgrade..stupid me didnt check if there are issues with the latest version before i upgraded.  Is there a way to downgrade on Fdroid without losing settings?

In addition to the error applying rules, i also have tested the connections while using a VPN and while not using a VPN. It seems that switching between WiFi and Data while VPN is paused runs firewall rules in the background. And some connections did go through while VPN was paused even though i only allowed through VPN only.

Ive seen that once it says "error applying rules", it then says "successfully applied rules", but still i dont trust that it ran the rules successfully each time.

It also seems to me as OP mentioned, that it has something to do with both ipv4 and ipv6 running concurrently. As before this never used to be a problem with v3.4.0.

@ukanth have you found what the issue is?

Im not sure how safe it is to disable ipv6?

Oneplus 6T, Android 9

**Comment by Hr46ph** [comment] 2021-05-14 12:20
Same problem, same work around applies (disable ipv6).

I've restored the previous version as Im sure disabling ipv6 is the same as running no afwall, provided that you actually have an ipv6 address :P.

**Comment by ukanth** [comment] 2021-05-16 02:13
Anyone try this release and let me know if this solves the problem with ipv6 enabled ? 

https://drive.google.com/file/d/12cH50Hi47RvhqpJPQt64FierveMSRzLD/view?usp=sharing

**Comment by Hr46ph** [comment] 2021-05-16 06:48
> Anyone try this release and let me know if this solves the problem with ipv6 enabled ?
> 
> https://drive.google.com/file/d/12cH50Hi47RvhqpJPQt64FierveMSRzLD/view?usp=sharing

Thanks for the quick action!

I seem to require permission to download it, which I requested from some weird looking email address :).

**Comment by ukanth** [comment] 2021-05-16 07:37
you should be able to download it now.

**Comment by Hr46ph** [comment] 2021-05-16 08:53
> you should be able to download it now.

Yes, installed it and it installed as a second version alongside 3.4.0 (donate).

I should mention I use EdXposed as well. 3.5.2 installed a new module which I enabled (and disabled the old version), rebooted the phone.

I went ahead uninstalled 3.4.0 after exporting the current filter rule list and imported it in 3.5.2. Checked ipv6 is enabled and enabled / applied the rules.

No more errors, all applied succesfully.

Only thing remaining for me is to get donate version back so I can create my profiles again :).

Thanks for the quick fix!

**Comment by infinity0** [comment] 2021-06-24 13:40
I am using 3.5.2.1 with the same problem unfortunately. Disabling IPv6 makes things work again, but of course this is not ideal.

**Comment by infinity0** [comment] 2021-06-24 13:41
I also have edXposed installed. I tried both enabling and disalbing the AFWall+ module in edXposed and the bug remains in both cases; and in both cases disabling IPv6 works around the bug.

**Comment by MarcoHannemann** [comment] 2021-06-25 11:46
> 
> 
> I am using 3.5.2.1 with the same problem unfortunately. Disabling IPv6 makes things work again, but of course this is not ideal.

I can confirm this behaviour in 3.5.2.1, disabling IPv6 support "fixes" it. POCO F1 with LineageOS 18.1 installed.

**Comment by DanielRieken** [comment] 2021-09-08 20:27
I can confirm this behaviour in 3.5.2, Oneplus 6T with Android 11.

logs:
[IPv4rules.log](https://github.com/ukanth/afwall/files/7131263/IPv4rules.log)
[IPv6rules.log](https://github.com/ukanth/afwall/files/7131265/IPv6rules.log)

@ukanth have you found what the issue is? do you need more informations to debug?
3.4.0 seems to be working without problems...

**Comment by DanielRieken** [comment] 2021-09-09 14:09
I can confirm with IPv6 disabled (see attached screenshot), it works for me. I've tested with system- and build-in iptables.
![Screenshot_20210909](https://user-images.githubusercontent.com/68472253/132701487-fc2b6653-e1ee-4d98-b077-d0f6889c08e8.png)

**Comment by ukanth** [comment] 2021-09-15 15:44
can you try this version ?

https://www.dropbox.com/s/f1fekfxpqmvw2mg/AFWall%2B_3.5.3_BETA1.apk?dl=0

**Comment by DanielRieken** [comment] 2021-09-16 08:23
@ukanth 
this looks very promising! 👍✌️
I've applied the rules 50 times in a row and it worked. Before I got an error every 5th time. So it looks really good for me.
I can also confirm, when I uncheck the option "Add Delay", the error is back again...

Thank you so much for this beta-release!

I got 2 more question left:
- Is it possible to first apply IPv4 rules and then IPv6 rules?
- When in whitelist mode: in which order the rules are applied? first the "deny all"-rule and then the "allow"-rules for each application? or first the "allow"-rule and then the "deny all"-rule? In other words: when it takes ~8 seconds to apply the rules, is there any chance for an application to connect to the internet within this short timeframe, because the "deny all"-rule is not yet set?

https://user-images.githubusercontent.com/68472253/133575674-0db18932-99d5-4b5b-a2ba-e9866d3bee0b.mp4

**Comment by ukanth** [comment] 2021-09-16 16:38
It was the case before. IPv4 followed by IPv6 and I introduced  parallel call. But seems like some internal process changes which breaks that.

> DROP for IPv4 and IPv6
> Apply proper rules
> ACCEPT for IPv4 and IPv6 

this is the order in which it executes. when you manually apply it does full change of rules. But for connectivity it only updates ipaddress related chains (Wifi or Data), so its usually pretty quick.

**Comment by ngrigoriev** [comment] 2021-09-16 21:42
I have also noticed that it starts happening if I have really bad cellular network OR I am connected to a highly unstable WiFi network and the device flip-flops between WiFi and LTE. I observed it several times, last time it was the hotel WiFi network I just connected to. For some reason, if i starts happening, then it will most likely continue to happen unless I restart the phone.

**Comment by DanielRieken** [comment] 2021-09-17 06:16
> I have also noticed that it starts happening if I have really bad cellular network OR I am connected to a highly unstable WiFi network and the device flip-flops between WiFi and LTE. I observed it several times, last time it was the hotel WiFi network I just connected to. For some reason, if i starts happening, then it will most likely continue to happen unless I restart the phone.

@ngrigoriev is this also happening with 3.5.3_BETA1?

**Comment by lemmy04** [comment] 2021-09-17 09:35
this one here hints VERY strongly at a timing thing.

What I'm guessing is this:

1. device connects to wifi
2. afwall starts reapplying rules, which takes about a minute or so for 600+ applications
3. at some point during that time the OS does its "quality check" on the wifi connection, which fails because the firewall isn't open for that app yet
4. because of the failed test the OS pulls down the wifi again
5. AFwall starts another run of setting rules, which dies hard because the first one isn't done yet.
result: device is left with a mish mash of conflicting rules which won't even get cleaned up with a normal afwall run, you have to disable afwall, manually flush rules, and turn afwall back on.

**Comment by DanielRieken** [comment] 2021-09-17 16:38
>     2. afwall starts reapplying rules, which takes about a minute or so for 600+ applications

@ukanth is that true? does afwall really need to re-apply all of its application rules as soon as the device connects to wifi? i think that is nonsence, connectivity chances should be really fast...

**Comment by lemmy04** [comment] 2021-09-17 19:00
> > ```
> > 2. afwall starts reapplying rules, which takes about a minute or so for 600+ applications
> > ```
> 
> @ukanth is that true? does afwall really need to re-apply all of its application rules as soon as the device connects to wifi? i think that is nonsence, connectivity chances should be really fast...

well i might have exaggerated with the whole minute but it *does* take some time to apply the rules, to the point that android is led to believe that the wifi you just connected to doesn't actually have internet access...

**Comment by DanielRieken** [comment] 2021-09-17 20:47
> 
> 
> > >
> > >2. afwall starts reapplying rules, which takes about a minute or so for **600+ applications**
> > >
> > 
> > 
> > @ukanth is that true? does afwall really need to re-apply **all of its application rules** as soon as the device connects to wifi? i think that is nonsence, connectivity chances should be really fast...
> 
> well i might have exaggerated with the whole minute but it _does_ take some time to apply the rules, to the point that android is led to believe that the wifi you just connected to doesn't actually have internet access...

Although I think Android is not completely stupid and will run the tests over a longer period of time, I did not say that your theory is wrong!
However, my concern was not whether it would take a few seconds or a few minutes, but rather that the rules for the 600 applications don't need to be re-applied again.
As far as I understand, the application rules are applied **once at start** and on connection-changes it only updates ipaddress related chains (Wifi or Data), so its usually pretty quick. In other words: it is not important how many application rules you have, because they don't need to be re-applied...

**Comment by ukanth** [comment] 2021-09-20 06:05
As i mentioned earlier, connectivity changes do not perform full apply. AFWall+ chains are optimized to reduce the iptables rules when connetivity changes. But when the user forcefully apply rules via menu and when the devices boots first time it performs full rules apply.

**Comment by sn-00-x** [comment] 2021-09-20 08:11
same problem with stable here sometimes. seems to be fixed with 3.5.3_BETA1

**Comment by rsudev** [comment] 2021-09-29 21:16
I also had this issue (but not persistent enough to report).
With the beta it is fixed for me as well.

**Comment by allo-** [comment] 2021-10-04 21:54
I have the same issue and I suppose it is a problem with running commands in parallel:

> (3) Error applying iptables rules. Exit code: 4
> 
>    IPTables can exit with status 4 if two or more processes tries to update the same table again and again. See here for detailed information.

https://github-wiki-see.page/m/ukanth/afwall/wiki/Error-codes

But why is AFWall running hundreds of iptables processes? Can't it use `iptables-restore` with a text file with the rules? This would probably be much faster as well.

**Comment by Enkidu70** [comment] 2022-01-07 17:14
> can you try this version ?
> 
> https://www.dropbox.com/s/f1fekfxpqmvw2mg/AFWall%2B_3.5.3_BETA1.apk?dl=0

Until now, I used donate v3.5.2.

I had the same problem on my OnePlus 6T, RR 8.6.4 (Android 10) and  OnePlus 8T, crDroid 7.13 (Android 11), both Magisk + LSPosed.

Beta works fine on both! Thank you very much.

But how can I get donate back on beta version? @ukanth

**Comment by Kosh83** [comment] 2022-01-18 02:31
Ty @ukanth  for the beta version, you are on to something cause the problem went away for me as well.
I'm normally on the donate v3.5.2 (which i paid for) and i am wondering the same as the post above, will the beta version soon be released as a stable working version so we can utilitize all functions? (I miss the log settings).

I'm on a Poco X3 Pro with A11 ArrowOS+Magisk and got the same issue, i need to disable ipv6 to enable rules. (it works fine on my old phone using A10 ArrowOS if that helps?

**Comment by ukanth** [comment] 2022-01-20 05:36
Yes. I know beta version fixes this problem. but that's not a permanent solution. In beta, it applies v4 and v6 rules with delay of 1s. But I wanted the rules to be applied asynchronously/parallel.

**Comment by Fry-kun** [comment] 2022-01-27 17:59
Still seeing weirdness with the beta, numbers jumping all over the place (not every time)


https://user-images.githubusercontent.com/1214224/151416690-133225e8-a1d8-4836-879b-a0c3541174fc.mp4

**Comment by jensMF** [comment] 2022-01-28 12:21
I have this issue as well, but as I could not add new information I never comented here.
But now, all of a sudden, I have a new error message:
```
command 'ip6tables -A afwall-tether -m owner --uid-owner 0 -p udp --sport=53 -j RETURN' exited with status 4
Output:
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
```
I have this on two devices and am on version 3.5.2.1

**Comment by DanielRieken** [comment] 2022-01-28 12:27
> I have this on two devices and am on version 3.5.2.1

Can you try 3.5.3_BETA1?

**Comment by selankon** [comment] 2022-02-28 18:36
Same error with a lineageOs  18.1 android 11 AfWall 3.5.2.1

If I disable ipv6 support works fine

**Comment by DanielRieken** [comment] 2022-03-02 05:04
> Same error with a lineageOs 18.1 android 11 AfWall 3.5.2.1
> 
> If I disable ipv6 support works fine

Can you try 3.5.3_BETA1?

**Comment by Fry-kun** [comment] 2022-03-02 05:09
I think Play store updated to 3.5.3 and the problem is back 😭
Couldn't downgrade to 3.5.3_b1 for some reason, either

**Comment by DanielRieken** [comment] 2022-03-02 22:53
> I think Play store updated to 3.5.3 and the problem is back 😭 Couldn't downgrade to 3.5.3_b1 for some reason, either
> […](#)


For me the latest version on [Google Play](https://play.google.com/store/apps/details?id=dev.ukanth.ufirewall&hl=en&gl=US) is 3.5.2:

![352](https://user-images.githubusercontent.com/68472253/156463338-bc9f858b-a3ae-484c-9cbf-056717f7dc82.png)

**Comment by CircuitSerialKiller** [comment] 2022-04-01 11:58
I'm having this issue in 3.5.3 with LineageOS 18.1, and was having it on another OnePlus phone with OOS9. I can confirm disabling IPv6 support solved this issue. Thankfully IPv6 support isn't important to me and I can disable IPv6 in my phone/afwall to prevent data leaks. From what I've read in the comments above, I wonder if an option to apply IPv6 rules after IPv4 rules would solve this issue?
Thanks everyone for the tip on disabling IPv6 (and then blocking all IPv6).

![Screenshot_20220401-073716_Logcat_Reader_1](https://user-images.githubusercontent.com/13612914/161258456-e4dcae6e-3260-4569-9e20-8c850ceaaee8.png)

**Comment by allo-** [comment] 2022-04-01 16:47
Did someone try to use `iptables-restore`? It will probably be much faster anyway and reduce the time for applying the rules and the time when possibly no rules are in effect a lot.

**Comment by intika** [comment] 2022-06-30 04:28
donate version updated from 3.5.2 to 3.5.3 and I got this issue...
finally I get it solved by exporting and importing the settings... hope I wont see that error later on... (I did not tested extensively)...
If it was really that I had probably some left over rules from apps without internet permission or uninstalled apps and the new version of afwall did not like that... wait and see...

**Comment by Enkidu70** [comment] 2022-06-30 23:17
Same issues with applying rules with 3.5.3 as with 3.5.2. beta1 still works fine.

(When the error occurs, most times it helps to
1. disable firewall
2. clear rules (show rules / delete rules)
3. clear app cache
4. force stop afwall
5. start it & apply rules)

**Comment by ukanth** [comment] 2022-07-01 11:04
You should enable delay in preferences. I enabled it by default in beta, but not in production release

**Closed as completed** 2022-07-06 12:21 UTC
Labels: Review

**Comment by CircuitSerialKiller** [comment] 2022-09-23 10:47
I have been having the problem described above with 3.5.3 with both OP6 and OP8T, stock firmware. Disabling ipv6 support in AFWall works around the issue, however that's not a solution since you'd then have to somehow disable ipv6 on your phone, in a method that survives reboots, SIM swaps, etc. first to prevent apps from leaking your personal data via ipv6 (ie via APN settings), which is not optimal. When I enabled the 1s delay in preferences for the workaround described above in either OP6 or OP8T, I immediately get "Error applying iptables rules" before any rules are applied. 

Logcat just shows 
command 'iptables=/system/bin/iptables -w 1' exited with status 127
Output:

For the 8T, in preferences, I switched the iptables binary to "Built-in iptables", and that seems to have worked around the issue with the workaround. 

If I try the same workarounds in the 6T, I see the IPv6 rules get stuck applying at a certain point, and AFWall still reports success. 

Also, on both devices, most of the time I see "Log is empty" when trying to view the log, even though blocks show up in dmesg.
