### ISSUE TITLE
Support for Android TV/Nvidia Shield ?

### ISSUE THREAD

**Issue by GitJamz** [ukanth/afwall#1145] opened 2020-09-27 07:52 UTC
Hi,

I would love to be able to use AFwall on android TV or specifically on Nvidia Shield TV.

I tried a few months ago to install the apk but I remember the interface was not suiteable to use and I could not click things and configure the app.

Is this possible to request or make work somehow? This device is very popular and Im sure there are many more that want this feature.

**Comment by ukanth** [comment] 2021-03-07 13:11
Duplicate of #1154

**Closed as completed by ukanth** 2021-03-07 13:11 UTC
