### ISSUE TITLE
App does not block traffic on Android 9 Pie 

### ISSUE THREAD

**Issue by Jocky92** [ukanth/afwall#880] opened 2018-10-10 08:14 UTC
Im using Afwall version 2.9.9 on my Pixel Phone with the newest Android 9 build PPR2.181005.003

I used the app with Android 8 and everything worked fine nur after the Update to 9 the App cannot block my Connection for the Apps. I activate ipv6 but without any difference all Apps still have internet connection.

Is there a way to fix this?

**Comment by DavidVentura** [comment] 2018-10-10 16:21
check https://github.com/ukanth/afwall/issues/850

**Comment by ukanth** [comment] 2018-10-13 15:38
Duplicate of  #850

**Closed as completed by ukanth** 2018-10-13 15:38 UTC
Labels: Duplicate
