### ISSUE TITLE
V3.3.1 had better GUI main screen than the latest version 3.4.0

### ISSUE THREAD

**Issue by ghu1234** [ukanth/afwall#1078] opened 2020-02-09 13:38 UTC
V3.3.1 had better GUI main screen than the latest version 3.4.0
Instead of splitting the app and the options into two lines, one single line was lot better and more readable. I accidentally mistook one app for another's permissions and changed it with this version. 

I have couple of friends that also shared the same view. Would appreciate a rollback to previous looking GUI.

**Comment by ukanth** [comment] 2020-02-09 13:41
Duplicate of #1069

**Closed as completed by ukanth** 2020-02-09 13:41 UTC
