### ISSUE TITLE
integrate notification filter into main app rules list

### ISSUE THREAD

**Issue by Maxxee** [ukanth/afwall#798] opened 2018-01-23 09:32 UTC
I think it makes no sense to have the notification filter as a separate view.
Please integrate the notification filter into the main app rules list by simply adding a logging checkbox to each list entry.
Thanks in advance.

**Comment by ukanth** [comment] 2018-03-20 17:07
Duplicate of #806

**Closed as completed by ukanth** 2018-03-20 17:07 UTC
Labels: Duplicate
