### ISSUE TITLE
Log service not working app reports "Log is empty" 

### ISSUE THREAD

**Issue by ioogithub** [ukanth/afwall#1065] opened 2020-01-14 23:14 UTC
I have been testing AFWall+ but can never get the logs to work. No matter what I do they are always empty.

When I click on View Log, I see a message "Please enable log service via Preferences. If enabled, then go log data.

I verified that under Preferences-Log "Turn on log service" is checked.

I have been testing for a few days now and I have never seen any log entry. I have reinstalled a few times.

Toggling between new view and old view does not do anything.

I can see this was an issue that was reported solved a few version ago. It looks like it is still present. Does anyone have a work around?

Version: AFWall+ 3.3.1
OS: LineageOS (latest nightly)
Root: Magisk 20.3
Device: Motorola g7

**Comment by irontechmonkey** [comment] 2020-01-25 16:40
FYI, While testing an issue that may or may not be related to this one I may have found a workaround to this one... which might then take you into the second issue. 

If you change Preferences > Logs> Log target (change from NFLOG to LOG (note there seem to be NFLOG choices) might induce logging, but then the second issue, FC upon attempt to view log may (or may not) occur. 

See this ticket for more details: https://github.com/ukanth/afwall/issues/1067

**Comment by gab12** [comment] 2020-05-13 13:29
I have the same problem with AFWall 3.4.0 on Android 10.
The workaround ( change log target) didn't work but I have find an other workaround.
I installed BusyBox and I changed Preferences > Logs> Method by Busybox

Version: AFWall+ 3.4.0
OS: Android 10 Samsung Stock
Root: Magisk 20.3
Device: Samsung A50

**Comment by ukanth** [comment] 2021-03-06 16:18
Duplicate of #1002

**Closed as completed** 2021-03-06 16:18 UTC
