### ISSUE TITLE
Error applying rules on Xperia 10 III

### ISSUE THREAD

**Issue by dec0de** [ukanth/afwall#1234] opened 2021-08-23 15:58 UTC
**Describe the bug**
After configuring your firewall enabling/applying rules will create an error message (and no rules will be applied)

**Firewall Logs**
It's not really applicable here...

**Smartphone (please complete the following information):**
 - Device: Xperia 10 III
 - Android OS: 11

**Additional context**
A temporary solution seems to be to unbox the "IPv6 support" box and re apply the config.

**Comment by MarcoHannemann** [comment] 2021-08-23 18:22
This issue has been already reported, see #1206

**Comment by ukanth** [comment] 2021-08-26 04:38
Duplicate of #1206

**Closed as completed by ukanth** 2021-08-26 04:38 UTC
Labels: Duplicate
