### ISSUE TITLE
Constantly requesting root

### ISSUE THREAD

**Issue by peterfajdiga** [ukanth/afwall#616] opened 2016-11-12 11:13 UTC
Since updating AFWall, the root icon is always present in the upper right corner (I'm using cyanogenmod). If I open AFWall and exit it, the icon temporarily disappears, but soon reappears.

In older version this behavior could be averted by disabling Active rules, but I still had to open and exit the app after booting.

I think the app should relinquish its root rights after doing what it needs them for.

**Comment by ukanth** [comment] 2016-11-12 13:00
Duplicate of #480 

Read this post, https://github.com/ukanth/afwall/issues/480#issuecomment-172282818

**Comment by peterfajdiga** [comment] 2016-11-13 11:50
My apologies, I should have searched before posting. Still, I may have reported something new: disabling the Active rules setting doesn't really prevent applying rules on every connectivity change anymore. Steps to reproduce:
-disable Active rules
-exit AFWall
-toggle wifi or data
-observe AFWall acquire root (on cm it's visible because of the hash icon)

I'm using version 2.8.0

Anyway, thanks for the app and keep up the great work :)

**Comment by ukanth** [comment] 2016-11-13 13:29
This could be because of Log service. Because log service is now required root to clear of the existing log shell service on connectivity change.

**Closed as completed** 2017-02-24 03:28 UTC
Labels: Duplicate
