### ISSUE TITLE
[ISSUE] Log is empty, no notification if app is blocked

### ISSUE THREAD

**Issue by 9jS2PL5T** [ukanth/afwall#1164] opened 2020-12-14 12:41 UTC
- Log is activated, but there isn't any app in the list. (maybe because notification of apps who are trying to connect with the internet is disabled, but it would be nice if those apps are still can be seen in the log)
- I do not get a notification if an app is blocked.

Samsung M30s, Android 9

**Comment by ukanth** [comment] 2021-03-06 16:19
Duplicate of #1002

**Closed as completed by ukanth** 2021-03-06 16:19 UTC
