### ISSUE TITLE
Feature Request: A UI for rules editing. 

### ISSUE THREAD

**Issue by TriMoon** [ukanth/afwall#252] opened 2014-01-31 13:33 UTC
What I miss most on this app is a User-interface (UI) to add/edit/remove custom rules.
If done well it would also eliminate errors like illegal chars.

I imagine the UI to be like this or or similar:
<ol>
	<li><em><b>Multi-view</b></em> of current rules:<ol>
		<li>A view like it is now, listing all apps.</li>
		<li>A view per chain.</li>
		<li>A view per application (user id)</li>
	</ol></li>
	<li><em><b>Short tap</b></em> on an entry:<br />
		Current functionality to view the log entries related to the one tapped.<br />
		Or switch to view-mode (1.iii)</li>
	<li><em><b>Long tap</b></em> on entry:<br />
		In all views except the overview mentioned in (1.i) view-mode.<br />
		A pop up with edit/remove option for the entry.</li>
	<li><em><b>Edit/Add entry</b></em> mode:<ol>
		<li>Checkbox + listbox with UID's available on the device.<br />
			When the checkbox is selected, the entry will only apply to the UID selected in the listbox.<br />
			The listbox should be automatically populated with the current available UID's on the device and it's entries accompanied with the description of the corresponding application for visual ease.</li>
		<li><em><b>Input part</b></em> of rule.<ol>
			<li>A listbox to select the protocol type,  like ANY/TCP/UDP/ICMP etc.</li>
			<li>A textbox to enter the <b>source</b> address in <a href="https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing" title="Classless Inter-Domain Routing">CIDR</a> format.</li>
		</ol></li>
		<li><em><b>Output part</b></em> of rule.<ol>
			<li>A listbox to select the protocol type,  like ANY/TCP/UDP/ICMP etc.</li>
			<li>A textbox to enter the <b>destination</b> address in <a href="https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing" title="Classless Inter-Domain Routing">CIDR</a> format.</li>
		</ol></li>
		<li><em><b>Target part</b></em> of rule.<ol>
			<li>A radio selection to select the jump target of the rule, to select either:<ol>
				<li>Build-in targets like REJECT/DROP/etc.</li>
				<li>Chain names that are available.</li>
			</ol></li>
			<li>A listbox to select from, the automatically populated, entries of the choice of the radio selection.</li>
		</ol></li>
		<li>A <em><b>commit button</b></em> ofcourse.</li>
	</ol></li>
</ol>

Feel free to comment, im sure there is more that can be added that i forgot now :)

**Comment by ukanth** [comment] 2016-08-03 06:19
Duplicate of #15

**Closed by ukanth** 2016-08-03 06:19 UTC
Labels: Feature
