### ISSUE TITLE
Feature Suggestion - Screen on/off  rules

### ISSUE THREAD

**Issue by EMK2000** [ukanth/afwall#678] opened 2017-02-15 05:17 UTC
I have seen some other non-root firewall that can control the data traffic for screen on/off separately. Can your app also add this feature?

**Comment by Zulgrib** [comment] 2017-02-23 01:23
You can set two different profile and switch them using tasker or similar

**Comment by ukanth** [comment] 2017-02-23 15:39
Duplicate of #492

**Closed as completed by ukanth** 2017-02-23 15:39 UTC

**Comment by SkyWheel** [comment] 2017-10-10 05:52
@Zulgrib , could you please clarify how to do this? Never used a tasker before...
