### ISSUE TITLE
FC upon attempt to view log.

### ISSUE THREAD

**Issue by irontechmonkey** [ukanth/afwall#1071] opened 2020-02-01 13:08 UTC
LOS 15 Oreo, Magisk 20.3/7.5.1, Afwall+ 3.4.0 BETA2

- Update Afwall+ to 3.4.0 BETA2.
- Reboot.
- No logging; indicated by no toasts and ability to view empty log.
- Change log target to log.
- Toasts OK but attempt to view log FC. 

(Incoming) Attached logcat captures FC.

[Beta22020-02-01-07-29-23.txt](https://github.com/ukanth/afwall/files/4143227/Beta22020-02-01-07-29-23.txt)

[Beta2IPv4rules.log](https://github.com/ukanth/afwall/files/4143228/Beta2IPv4rules.log)

**Comment by ukanth** [comment] 2021-03-12 11:29
Duplicate of #1144

**Closed as completed** 2021-03-12 11:29 UTC
Labels: Review
