### ISSUE TITLE
[ISSUE] Afwall fails to apply rules on some network changes

### ISSUE THREAD

**Issue by Fry-kun** [ukanth/afwall#1262] opened 2022-01-20 17:04 UTC
**Describe the bug**
Afwall fails to apply rules on some network changes. This happens very often when leaving wifi area & switching to cell data only.
It's extremely disruptive, it's hard to even disable the rules to get the phone into a working state. The only thing that seems to work consistently is rebooting the phone altogether, which is not a good workaround.

It's worth noting that the failure and/or success notices sometimes pop up twice, indicating that there might be 2+ processes trying to do the same thing.
The progress indicator also behaves strangely when there's an error: instead of a steady climb of numbers (100..150..300..500..), it jumps up and down between single/double digits & triple digits (20..100..45..200..70..300..) (note: pulled these numbers out of thin air, just trying to describe the general behavior. Let me know if you need me to capture this madness on video or anything)

**Firewall Logs**
Several unrelated attempts [logs.tar.gz](https://github.com/ukanth/afwall/files/7907086/logs.tar.gz)

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro (raven)
 - Android OS: 12

**Additional context**
This has been happening a lot lately (with this new phone, possibly because it's using 5G and/or whatever else?)

**Comment by ukanth** [comment] 2022-01-21 03:38
Have you tried latest BETA ?

**Comment by Fry-kun** [comment] 2022-01-21 03:42
I'm in beta program in the Play Store but there isn't one available yet...

**Comment by ssivtsov** [comment] 2022-01-23 14:45
Have the same behavior on OnePlus 9R, Android 11

**Comment by Fry-kun** [comment] 2022-01-23 23:23
Hello?
Where/how do I access the beta? If I need to sideload it, where from?

**Comment by ukanth** [comment] 2022-01-24 04:04
https://www.dropbox.com/s/f1fekfxpqmvw2mg/AFWall%2B_3.5.3_BETA1.apk?dl=0

**Comment by Fry-kun** [comment] 2022-01-24 22:10
Thanks.

Aside, a security app like a firewall shouldn't be distributed through a Dropbox link.
Play store definitely supports beta distro, and though I haven't tried it,
it shouldn't be too complicated to use.
Don't know if you use Firebase, but it has some beta distribution features
as well.
F-Droid has very limited support, but supposedly it's also doable there.
And of course GitHub actions could easily build the alphas/betas, see
Magisk for example..

**Comment by Fry-kun** [comment] 2022-01-25 01:16
With the beta, applying doesn't fail but I'm seeing this strange behavior

https://user-images.githubusercontent.com/1214224/150892217-175d17ea-8341-4f94-ac6c-3bd8697ca68b.mp4

Seems like the beta simply applies a lock which prevents 2 instances from updating at the same time. It's much better than not being able to apply the settings, but not a complete fix, IMHO

**Comment by ukanth** [comment] 2022-01-25 02:57
Duplicate of #1206 

https://github.com/ukanth/afwall/issues/1206.

Read my last comment on that thread.

**Closed as completed by ukanth** 2022-01-25 02:57 UTC
Labels: Duplicate

**Comment by DanielRieken** [comment] 2022-01-27 23:09
> With the beta, applying doesn't fail but I'm seeing this strange behavior
> apply.mp4
> 
> Seems like the beta simply applies a lock which prevents 2 instances from updating at the same time. It's much better than not being able to apply the settings, but not a complete fix, IMHO

you're more than welcome to post a pull request, IMHO

**Comment by Fry-kun** [comment] 2022-01-27 23:20
I have not actually read the code, this was just an observation, trying to
help.
I don't have the time right now for reading/updating this code; this is why
I already donated toward development :P
