### ISSUE TITLE
MIUI second space applications invisible for AFWall+

### ISSUE THREAD

**Issue by retakal** [ukanth/afwall#574] opened 2016-09-06 09:04 UTC
Hi,

as you might know MIUI 8 comes with the abillity to clone apps so that you can run two instances of them. By this you could have e.g. multiple separate whatsapp accounts. Unfortunately the AFWall+ doesn't list the cloned app. Only within the log you could see that the cloned app is blocked.

Any idea how if this will be supported in the future? 
Or any workaround thinkable? Would I be able to allow it with donate version?

Thanks

**Comment by ukanth** [comment] 2016-09-07 03:14
I don't use MIUI, what is use of multi instance of AFWall+ Is it similar to multiuser feature of Android ?

**Comment by retakal** [comment] 2016-09-07 15:37
Thanks for commenting.
Hmm, I don't think it is similar to multiuser feature of Android. Unfortunately I didn't find additional information on how exactly it works.

But probably it works similar like "App Cloner" or similar other apps...

What would happen, if I have the donate version and click on the log-entry? Could I configure it then to be allowed?

**Comment by ukanth** [comment] 2016-09-07 15:44
I need to check how the uid works for cloned apps. Do you have the uid for both ?

**Comment by retakal** [comment] 2016-09-07 15:52
cloned one is 99910050
original is 10050

**Comment by ukanth** [comment] 2016-09-07 16:04
So, you don't see the second app on the list. Can you try force reloading (swipe down) ?

**Comment by retakal** [comment] 2016-09-07 16:12
Only in the log of blocked apps but not on the list with the check boxes

On September 7, 2016 6:04:50 PM GMT+02:00, ukanth notifications@github.com wrote:

> So, you don't see the second app on the list ? 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ukanth/afwall/issues/574#issuecomment-245330973

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by retakal** [comment] 2016-10-04 09:50
Any update on this?
What would happen within donate version, if I click on the item in the log of blocked apps? Would I be able to set an allow flag from there?

**Comment by ukanth** [comment] 2017-02-24 02:55
Duplicate of #271

**Closed as completed by ukanth** 2017-02-24 02:55 UTC
Labels: Feature
