### ISSUE TITLE
Notification of new installed app

### ISSUE THREAD

**Issue by walrus543** [ukanth/afwall#595] opened 2016-10-12 13:19 UTC
Hi,
When I select the AFWall+ notification of a new installed app, the app is not listed at the top of the list (main screen).
With the previous version of AFWall+, it was not necessary to search the new app since it was on the first line.

Could you bring it back?
Thank you.

**Comment by ukanth** [comment] 2016-10-13 02:53
It works, over the time/updates, this behavior start appearing. Since I can't reproduce this, I would need your help.

**Comment by walrus543** [comment] 2016-10-13 12:29
Of course, tell me what you need.

[Here is](https://webcloud.zaclys.com/index.php/s/xJSwgPwIWIU21aZ/download) a video to show you how it occurs.

AFWall+ information:
version code: 15601
version: 2.6.0.1

My setup:
Nexus 5
Android 6.0.1 - Dirty Unicorns ROM (based off AOSP)
microG framework + FakeGapps
no Gapps except Play Store

**Comment by ukanth** [comment] 2016-10-15 10:23
Can you install an application which you have never installed before ( app which has internet permission ) and see if that appears on top ?

**Comment by walrus543** [comment] 2016-10-17 07:54
Done with Opera VPN. It doesn't appear on top.

**Comment by walrus543** [comment] 2016-10-20 08:37
FYI I have installed Bubbleupnp app and the app was on top after pressing the notification.

**Comment by ukanth** [comment] 2016-10-20 08:47
@Primokorn , Thanks for letting me know about it. This feature was never changed from Droidwall. I guess this is the time I should change this design and make it more clean. But it is not high priority right now.

**Comment by walrus543** [comment] 2016-10-21 06:41
No problem.
You are right, there's no rush.

**Comment by ukanth** [comment] 2016-11-06 06:55
This issue is fixed now.

**Closed as completed by ukanth** 2016-11-06 06:55 UTC
Labels: Bug, Low
