### ISSUE TITLE
beta: notification filter is empty

### ISSUE THREAD

**Issue by jancm** [ukanth/afwall#820] opened 2018-04-08 21:48 UTC
I don't get a list of installed apps to choose from in the log notification filter.

**Comment by RDJ16** [comment] 2018-05-10 18:28
i have the same problem with v2.9.9 only [1020]mDNS is available

**Comment by RDJ16** [comment] 2018-05-10 18:45
https://github.com/ukanth/afwall/issues/816

**Comment by ukanth** [comment] 2021-03-12 11:05
Duplicate of #816

**Closed as completed by ukanth** 2021-03-12 11:05 UTC
Labels: Review
