### ISSUE TITLE
AFWall+ blocking everything even though turned off

### ISSUE THREAD

**Issue by SecUpwN** [ukanth/afwall#355] opened 2015-03-19 06:25 UTC
Good morning @ukanth!

The good thing first: I still **LOVE** your App and the work you're doing here! Sadly, AFWall+ is mocking around lately (it worked before): It blocks everything even though turned off right from starting my phone.

That means, when starting my phone I have to _enable_ and then _disable_ AFWall+ to even get any internet connection. On the other hand, even if I do _not_ restrict anything and just turn AFWall+ on, it still blocks my whole internet connection - no matter if I change the binaries to be used in the settings.

**Technical Details**
- AFWall+ v1.3.4.1
- System: AOKP 4.4.4
- Phone: HTC One
- BusyBox: v1.23.1 in `/system/xbin` via BusyBox Pro

With this Issue, I'd also like to file a request to add some sort of Debugging-Button into the Help-Button of the AFWall+ menu. It will ease the collection of relevant data to solve future Issues of other users.

**Comment by ukanth** [comment] 2015-03-19 08:40
You can send the error report from menu->firewall rules-> Send error report.

**Comment by SecUpwN** [comment] 2015-03-19 09:09
>You can send the error report from menu->firewall rules-> Send error report.

That is pretty hidden. Please highlight that in the In-App FAQ. Here is the [logfile](https://defuse.ca/b/X0NMSPSV.

**Comment by CHEF-KOCH** [comment] 2015-03-19 12:19
[Hidden?](https://github.com/ukanth/afwall/wiki/HOWTO-Report-Bug)

**Comment by SecUpwN** [comment] 2015-03-19 12:21
>Hidden?

@CHEF-KOCH, not here, but within the App itself.

**Comment by cernekee** [comment] 2015-03-19 13:27
> It blocks everything even though turned off right from starting my phone.

Is "fix startup data leak" enabled?

**Comment by CHEF-KOCH** [comment] 2015-03-19 13:34
> That means, when starting my phone I have to enable and then disable AFWall+ to even get any internet connection.

I guess such behavior usually comes from the startup script. You could try to disable it and look it that helps. Also make sure you disabled the IPv6 option since it's [confirmed as bugged](http://www.kuketz-blog.de/afwall-die-alternative-zu-droidwall/). 

I also recommend to play with the binary stuff (never got any seriously troubles with afwall's integrated BusyBox & iptables - according to your log BB is already changed to builtin) + try to change the DNS option. 

About that FAQ thing, it's easy to fix and I submit a patch now because it's a good idea.

**Comment by SecUpwN** [comment] 2015-03-19 16:23
Thanks for helping me out, folks. The connection still does not work, even when playing with the binaries or disabling the IPv6 as well as "fix startup data leak". Anything else I should try out?

**Comment by CHEF-KOCH** [comment] 2015-03-21 09:39
I guess it's because your phone and rom is very new, you are the first here with an AOKP rom, nobody tested it with such rom until now. 
The strange thing is that I found out that your maximum transmission (MTU) seems wrong. [An MTU of 2000 isn't possible](http://phil.lavin.me.uk/2012/01/maximum-transmission-unit-mtu-explained/), only 1480/1492 + 20/8 = [1500 is possible](http://en.wikipedia.org/wiki/Maximum_transmission_unit). So without looking in the source there is something seriously wrong with the network code or driver, sure it's not really AFWall+ related but if this is already broken nobody knows what possible failure this rom contains. 

You can try another rom and report back if that "helps" if yes, make sure it's not a rom/network problem in general. As a workaround you could use the widget to faster toggle the status until we knows what's really going on, so wee need a boot log. But if all is disabled and it's still not working this must come from other problems.

You are using the BusyBox binary from the official "BusyBox app", that could also be a possible problem because some kernels/roms have problems with it, as written over [here](https://github.com/dorimanx/Dorimanx-SG2-I9100-Kernel/issues/26). I solved such thing by avoid using the BB app and compile it myself, there is also a guide and linked binary [here](http://forum.xda-developers.com/android/software-hacking/guide-busybox-snapshot-building-android-t2857650).

**Comment by SecUpwN** [comment] 2015-03-21 14:08
>I guess it's because your phone and rom is very new, you are the first here with an AOKP rom, nobody tested it with such rom until now.

Danke für Deine Hilfe, @CHEF-KOCH. But the failure can't be caused by the ROM since it used to work perfectly before until I had to re-install everything from scratch (formatted my whole phone on accident a few weeks ago when developing on [AIMSICD](https://secupwn.github.io/Android-IMSI-Catcher-Detector/)). Before switching to another ROM, I'd like to wait for a new AFWall+ release.

**Comment by CHEF-KOCH** [comment] 2015-03-21 15:57
Möglicherweise hast du mich etwas missverstanden, das sollte erst einmal eher als workaround dienen, bis wir was gefunden haben, allerdings ist das schwierig ohne Infos, wie gesagt ein Boot log wäre hilfreich oder etwas um zu sehen was das Internet blockiert (möglicherweise andere apps?) aber ohne genauere Sachen ist das reine Spekulation meiner Seite, allerdings bleibt die Tatsache das zumindest der MTU falsch ist was möglicherweise auf weitere Probleme hinweisen könnte. 
Ich nehme an das die alpha 2.x Version aus dem XDA Thread auch das selbe Problem hat, ggfs. müssen wir einfach mal nach gucken ob wir generell eine bessere Methode finden und ob das dann auch dann noch vorkommt (evtl. direkt init.d mit dem fix ausstatten oder gucken ob das HTC generell andere Netzwerknamen besitzt [leider unterstützt AFWall+ nicht alle möglichen Netzwerknamen da keine Liste dafür existiert]).

**Comment by CHEF-KOCH** [comment] 2015-03-21 15:57
Möglicherweise hast du mich etwas missverstanden, das sollte erst einmal eher als workaround dienen, bis wir was gefunden haben, allerdings ist das schwierig ohne Infos, wie gesagt ein Boot log wäre hilfreich oder etwas um zu sehen was das Internet blockiert (möglicherweise andere apps?) aber ohne genauere Sachen ist das reine Spekulation meiner Seite, allerdings bleibt die Tatsache das zumindest der MTU falsch ist was möglicherweise auf weitere Probleme hinweisen könnte. 
Ich nehme an das die alpha 2.x Version aus dem XDA Thread auch das selbe Problem hat, ggfs. müssen wir einfach mal nach gucken ob wir generell eine bessere Methode finden und ob das dann auch dann noch vorkommt (evtl. direkt init.d mit dem fix ausstatten oder gucken ob das HTC generell andere Netzwerknamen besitzt [leider unterstützt AFWall+ nicht alle möglichen Netzwerknamen da keine Liste dafür existiert]).

**Comment by SecUpwN** [comment] 2015-03-21 16:23
@CHEF-KOCH, herzlichen Dank für Deine Erklärung. Würde gern die Alpha 2.x-App mal testen ohne mich gleich für das BETA-Programm registrieren zu müssen. Wenn Du hier auf meinen Nutzernamen klickst, dann findest Du meine E-Post-Adresse. Würde mich freuen wenn Du mir die APK mal schickst.

**Comment by ukanth** [comment] 2015-03-22 03:57
I would appreciate if you guys speak in english !

**Comment by SecUpwN** [comment] 2015-03-22 14:05
@ukanth, sorry for us drifting into our native language. We've just talked about the testing of the very latest Alpha 2.x-App, which appears to reveal the same error. Also, @CHEF-KOCH recommended me to use another ROM to test if this Issue is related to AOKP - but it is not, since it worked perfectly before. He is also thinking that other Apps that I may have installed ight be the cause for AFWall+ not working as supposed to. If you have any further hints on what to try, please tell me.

**Comment by CHEF-KOCH** [comment] 2015-03-23 08:27
Another thing could be that some SuperSU settings may interference to get SU during the boot but without a log it's difficult to say. So the question is, if other scripts are also affected by this or only the affwallstart script?
Maybe you could try to this:
* Disable and reboot this SuperSU settings: <code>Mount namespace separation</code> + <code>Enable su during boot</code> + <code>Trust system user</code> (some settings may need a restart to take the effect e.g. mount namespace separation).
* Flash/place another script into init.d (make sure permissions are okay) 2000 2000 755 is normally enough (for shell).
* See in the LogCat if all was applied, in the meantime I'll write a debug script for affwalstart to see if all was applied during boot. 

I already wrote into another thread long time ago that we may think about to use a Xposed module for some stuff like this here, because it would be much easier to see debug stuff and it will fix other related problems for OS dependent stuff. But never got any feedback about my idea...

**Comment by SecUpwN** [comment] 2015-03-23 08:53
Thanks for your strong support, @CHEF-KOCH. The interesting thing to note, is that when I do the first step by disabling SuperSU settings `Mount namespace separation` + `Enable su during boot` + `Trust system user`, AFWall+ now lets all connections through - even the blocked ones. Getting another coffee.. :coffee: For the pure fun of testing it, I enabled everything I previously disabled - and AFWall+ now it lets most Apps pass the Firewall - but blocks Apps I haven't blocked! Huh, WTF? Here's [another logcat](https://defuse.ca/b/wGJJTEiX).

**Comment by CHEF-KOCH** [comment] 2015-03-23 11:07
> AFWall+ now lets all connections through - even the blocked ones.

I guess this behavior is "normal" (sad enough) because during the boot the system own iptables are in use. 
Well, I also wrote long time ago here on GitHub that we may start to replace the deprecated iptables from the system with our own (mostly working ones) or just replace the $PATH so that our stuff will be used, but nobody listen to me.... That will fix A LOT off problems especially during the boot but we have such workaround which is 70% useless because on almost every newer phone/rom it never gets applied, and more worst is the fact that people getting huge problems on Android 5.+ because the own iptables will not proper work there. But okay, .... (was a bit off-topic I know).

> For the pure fun of testing it, I enabled everything I previously disabled - and AFWall+ now it lets most Apps pass the Firewall

Mostly <code>Mount namespace separation</code> is here the stuff we need to looking at. But it's not really AFWall+ related because we only use some Superuser lib stuff and can't force the user to shut such option down (also not even with any scripts because that SU feature should fix some security related stuff). I will write a note in the FAQ but that's all we can do for now with this - maybe chainfire must change something but I guess he will not change something on this (yet). [Only 5 apps I know have some problems with that option]. 
Btw for each change on that option it needs an reboot, maybe it works just after re-enabling this stuff but normally it shouldn't after another reboot.

> ..... but blocks Apps I haven't blocked!
If the startup fix is on, this is okay until AFWall+ re-applies the iptables settings. 
But your fix is off according to your log, so I guess you talking about that. So, there could be multiple reasons for example the "download" category stuff was touched on the application(s) list and some other apps may need such service to get a connection. Or the app is right now running which means it usually needs some time to apply (re-apply) the settings (sometimes some apps need to be killed and restarted to apply the new settings).

But you can do us a favor and do the following:
* You need the Android SDK installed or as an alternative if you don't need this huge package, simply use the adb fast installer from [here](http://www.xda-developers.com/15-second-adb-installer-gives-you-lightning-fast-adb-fastboot-and-driver-installation/).
* Make sure you can connect to your device via USB (proper driver should be installed so that adb recognize your device, type _adb devices_ in cmd to check)
* Power off your device
* Start logging by entering this command on the command line: adb logcat >log.txt
* Power on your device
* Capture all stuff until AFWall+ was fully loaded (Please disable all other "security" related apps, like Xprivacy, LBE, security center of MIUI (if present),...) 
* Give us the log, maybe we see something more right after the boot which could make problems. 
* An SU only log would also help (make sure that the full capture of log from AFWall+ is enabled in the SuperSU app).

That's all we can do for now.

**Comment by SecUpwN** [comment] 2015-03-24 07:34
@CHEF-KOCH, thank you very much for your thorough answer crafted with your heart blood. I know that @ukanth and @chainfire are both very open-minded people. Would you guys please read the above answer and maybe be so kind to respond here if you guys add the proposed changes to your Apps?

**Comment by CHEF-KOCH** [comment] 2015-03-24 10:26
````
V/NatController(  198): runCmd(/system/bin/iptables -F natctrl_FORWARD) res=0
V/NatController(  198): runCmd(/system/bin/iptables -A natctrl_FORWARD -j DROP) res=0
V/NatController(  198): runCmd(/system/bin/iptables -t nat -F natctrl_nat_POSTROUTING) res=0
V/NatController(  198): runCmd(/system/bin/ip route flush cache) res=0
V/NatController(  198): runCmd(/system/bin/iptables -F natctrl_tether_counters) res=1
V/NatController(  198): runCmd(/system/bin/iptables -X natctrl_tether_counters) res=1
V/NatController(  198): runCmd(/system/bin/iptables -N natctrl_tether_counters) res=0
W/PackageManager(  587): Package dev.ukanth.ufirewall desires unavailable shared library com.sec.android.app.multiwindow; ignoring!
W/PackageManager(  587): Package dev.ukanth.ufirewall desires unavailable shared library com.sec.android.app.multiwindow; ignoring!
I/ActivityManager(  587): Start proc dev.ukanth.ufirewall for broadcast dev.ukanth.ufirewall/.BootBroadcast: pid=2618 uid=10087 gids={50087, 1028, 1015, 1023, 3003}
I/ActivityManager(  587): Killing 1650:org.vide
D/InitAlarmsService( 2104): Clearing and rescheduling alarms.
D/ActivityThread( 2618): handleBindApplication:dev.ukanth.ufirewall
D/ActivityThread( 2618): setTargetHeapUtilization:0.75
D/ActivityThread( 2618): setTargetHeapMinFree:2097152
D/AFWall  ( 2618): isWifiApEnabled is false
I/AFWall  ( 2618): Now assuming wifi connection
I/AFWall  ( 2618): IPv4 LAN netmask on wlan0: 192.168.2.185/24
I/AFWall  ( 2618): IPv6 LAN netmask on wlan0: fe80::867a:88ff:fe68:13b4/64
D/AFWall  ( 2618): Starting root shell...
I/AFWall  ( 2618): [libsuperuser] [SU%] START
I/ActivityManager(  587): Delay finish: dev.ukanth.ufirewall/.BootBroadcast
D/AFWall  ( 2618): Root shell is open
I/ActivityManager(  587): Waited long enough for: ServiceRecord{42e8a5c0 u0 dev.ukanth.ufirewall/.RootShell}
I/ActivityManager(  587): START u0 {cmp=dev.ukanth.ufirewall/.MainActivity bnds=[0,363][1080,555]} from pid -1
W/ActivityManager(  587): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x800000 cmp=dev.ukanth.ufirewall/.MainActivity bnds=[0,363][1080,555] }
I/ActivityManager(  587): Displayed dev.ukanth.ufirewall/.MainActivity: +663ms
I/ActivityManager(  587): Timeline: Activity_windows_visible id: ActivityRecord{42d99468 u0 dev.ukanth.ufirewall/.MainActivity t3} time:163417
D/AFWall  ( 2618): isWifiApEnabled is false
D/AFWall  ( 2618): CONNECTIVITY_CHANGE: interface state has not changed, ignoring
I/AFWall  ( 2618): BOOT_COMPLETED: applied rules
````
First I must read some more code from chainfires app to say if it really blocks something during the boot, sad it's not open source (except the stuff that isn't important).

All seems okay from AFWall+, except the fact that the .MainActivity takes a bit to long. From what I can see all rules gets applied on boot, so normally all should work.
With full SU log I meant that you enable full logging for AFWall+ in the SuperSU app and post the log here. 
But since I can't see much stuff that helps to get it working we could only try to replace the system iptables and add others and show if that solves the leakage problem. 

So the bad news is that I need some more time to test and run some configurations now to really understand what's going on behind the scene.

**Comment by SecUpwN** [comment] 2015-03-24 10:42
>So the bad news is that I need some more time to test and run some configurations now to really understand what's going on behind the scene. 

That is perfectly fine with me, @CHEF-KOCH. Take all the time necessary and don't stress yourself. I prefer if we find a solution here that enhances the overall performance of AFWall+ for all users. Thanks!

**Comment by Chainfire** [comment] 2015-03-24 11:43
I don't have that much to add here, I am not very familiar with AFWall+. 

I do see you mention ``mount namespace separation``, which really should have any effect on anything aside from filesystem mounts. I don't see how that would be related to AFWall+. On a side note, it is stated some apps have issues with it - if you are intimately familiar with that, please report to me which apps, on which configuration, and with which device (so: reproducable cases) so I may fix the problem, if the problem is on SuperSU's side (the app may also just be coded in an incompatible way).

``Enable su during boot`` should also not affect anything launched by Android (i.e. via a standard Android Service or Activity or whatever), though some issues have been reported about this on Lollipop that I'm still investigating. If something is started by ``init.d`` and that calls su, then that may be affected by this option as the Java layer is not loaded yet.

``Trust system user`` again should not be relevant unless a process already running as a non-app UID but also a non-root UID (so pretty much everything >0 and <AID_APP) calls su, I don't see why AFWall+ needs to do this.

As we've mentioned ``init.d`` anyway, it should be noted that it's operation is unreliable on any ``SELinux==Enforcing`` system, which is why SuperSU provides ``su.d``. 

The ``Waited long enough for: ServiceRecord{42e8a5c0 u0 dev.ukanth.ufirewall/.RootShell}`` line from the logcat is a tad worrying. Perhaps a ``logcat -v time`` which provides timing information as well would be more helpful. The ``RootShell`` class doesn't seem to be blocking the UI as far as I can see on a quick code skim, so I'm not sure what is going on there either. It's a very strangely constructed service though ( @cernekee )... You're just starting a background shell, and then also launching a dummy service in an attempt to keep the process from being killed off, with no further relation between them than both of them being defined in the same file ? While I guess that works, it's an odd construct.

**Comment by CHEF-KOCH** [comment] 2015-03-30 22:34
I found a quick solution for debugging with the iptables during the boot.

From the original docs:
> TRACE
> This target marks packes so that the kernel will log every rule which match the packets as those traverse the tables, chains, rules. (The ipt_LOG or ip6t_LOG module is required for the logging.) The packets are logged with the string prefix: "TRACE: tablename:chainname:type:rulenum " where type can be "rule" for plain rule, "return" for implicit rule at the end of a user defined chain and "policy" for the policy of the built in chains. It can only be used in the raw table.

Kernel needs the following stuff enabled (of course if no native Ipv6 just skip the ipv6 only stuff - because bindipv6 stux big time):
CONFIG_NETFILTER_XT_TARGET_TRACE
CONFIG_IP_NF_RAW
CONFIG_IP6_NF_RAW
CONFIG_IP_NF_TARGET_LOG
CONFIG_IP6_NF_TARGET_LOG
TRACE target - but should be enabled from >2.6.23 Kernels 

To add something to _/var/log/kern.log_ with TRACE we need to: 
- Create a new file on Linux/PC called _sysctl.conf_, and then <code>adb push sysctl.conf /system/etc/sysctl.conf</code> (if already present and activated just skip this step). 
````
adb shell 
modprobe ipt_LOG  (should be normally enabled by default)
modprobe ip6t_LOG  (should be normally enabled by default)
sysctl -p net.netfilter.nf_log.1=ipt_LOG
````

.. and this in our afwallstart script or external init.d:
```
# Example for ICMP Echo Packets add whatever you want with TRACE
iptables -t raw -D OUTPUT -p icmp -j TRACE
ip6tables -t raw -D PREROUTING -p icmpv6 --icmpv6-type echo-reply -j TRACE
````

The output can be catched via <code>/var/log/kern.log | grep 'TRACE:'</code> or the netfilter log.

If the rom includes tcpdump, we can also use this to see what's going on but it's only necessary for _nat:Post-/Prerouting_ source addresses (not necessary to see if something is loss or leaked. 

There is also:
* [gressgraph](http://freecode.com/projects/gressgraph)
* [dot-iptables](https://github.com/larsks/dot-iptables)
* [graph-iptables](http://search.cpan.org/~mamawe/App-Iptables2Dot-v0.2.1/bin/iptables2dot)
* [Afterglow](http://afterglow.sourceforge.net/index.html)
* [Real-time iptables monitor at perlmonks.org](http://www.perlmonks.org/?node_id=513732)
* [ipstate](http://linux.die.net/man/8/iptstate)
* or via LOGGING/LOGDROP but that cause several troubles (because I already tried to add <code> kern.warning = /var/log/custom.log (or/and /var/log/messages) in the sysctl and the output wasn't very detailed compared to TRACE

to see what's going on, in our case I recommend the mentioned TARGET stuff + ipstate which should work on "all" Kernels. 

So imho this would be nice:
```bash
`#!/bin/bash
debug() {
    if [ -n "$debug" ]; then
        $@ || echo -e "The error seems:\n$@"
    else
        $@
    fi
}
debug=1
IPTABLES="debug /sbin/iptables"

#afwallstartscript
$IPTABLES -P INPUT DROP
$IPTABLES -P OUTPUT DROP
.....
.....
````

**Comment by SecUpwN** [comment] 2015-05-14 12:52
@CHEF-KOCH, are there any other tests I shall execute to help you fix this?

**Comment by CHEF-KOCH** [comment] 2015-05-20 21:09
My iptables wrapper is done, the only stuff I need to change is to integrate BusyBox + Androids toolbox checks. The thing is that I don't think that this would solve or show additional problems we could really fix. After reading everything from chainfires page I think that the problem is still somehow between SU/ROM/BB and not AFWall+/iptables related especially since this is only during the boot (reboot). 

Maybe other modules/apps loading/blocking stuff like WifiProtector (this app use a useless busybox helper and BB 1.19.3 is already installed), Greenify, Xposed, Xprivacy, Avast - seems you using them all.

Please do the following:
- Freeze all mentioned apps and clear the cache from Xprivacy
- Ensure that you really use + !!! install correctly the very latest BusyBox (replacing the binary isn't enouth because symlink - BB has it's own -install command [see my article compile BB])
- Try to switch from SELinux enforcing to permissive (use _adb shell su 0 setenforce permissive_ or SELinuxModeChanger from F-Droid)
- If possible please give me the link to the ROM/Source


That's all for now, I know that isn't exactly that what you wanted to hear,....

**Comment by SecUpwN** [comment] 2015-05-22 06:14
>That's all for now, I know that isn't exactly that what you wanted to hear,....

Indeed. I thought you would just have another APK for me that I could test. Oh well.

>* If possible please give me the link to the ROM/Source

Have a look at my beloved [Android Open Kang Project](www.aokp.co). Currently still on [this KitKat release](https://s.basketbuild.com/filedl/devs?dev=aokp&dl=aokp/m7ul/aokp_m7ul_kitkat_nightly_2014-01-25.zip).

**Comment by CHEF-KOCH** [comment] 2015-06-09 15:25
Today I submitted a patch via email to possible solve that problem once and for all on AOKP Rom's.

**Comment by SecUpwN** [comment] 2015-06-10 12:16
>Today I submitted a patch via email to possible solve that problem once and for all on AOKP Rom's. 

**Awesome, thank you very much!** Thing is, @AOKP seems to be in a [halted position](http://aokp.co/blog/down-but-not-out) at this time and it is not quite clear when they'll be releasing new ROMs. Maybe you can also add the patch to AFWall+?

**Comment by CHEF-KOCH** [comment] 2015-08-25 10:38
This topic can be closed since AOKP is no longer under active development and I not think that there will be an come back according to an huge german page called heise (ct'). There was an interview with the developer and he promised (long time ago) to publish nightly's which never become true and now there is only a statement that this project is "on holding". In fact that mostly means "dead". 

However my patch was not merged with the latest source and now a lot of similar projects pop'ing up to claim to be the successor of AOKP but all are suffering from the same problem: less active developer. 

So after a lot of eMails and around 100 reboots I also revealed that AFWall+ is suffering from a major problem _security_ in the iptables, of course it's more indirect an AFWall+ related problem, we just need to adopt the changes and re-implement workarounds in our existent chains. In the mean time I updated the custom script section to provide some useful workarounds. If you use an hardened OS with strong SELinux you must be ensure that the mentioned table called _security_ (used for MAC) will be executed (see custom script section: flush/delete/resetting all rules as an example). Of course the tables _raw_, _filter_, _mangle_ & _security_ are not often used and are only for complex configurations involing in multiple routers, routing decisions and other stuff like that. So please remember at this point that AFWall+ isn't really designed for that much complexity. 

Overall I want to say with all this that switching to another ROM coasts less time against to debug things that are very complex and mostly ends up with time wasting. Of course to use another ROM isn't always possible, speaking about STOCK user (urgh STOCK!) but in such cases I would simply contact the developer or iptables developers and ask them to directly look in our project. To change things nobody knows much about it is very hard (or only a few peoples).


If another ROM suffering from a similar problem, feel free to open another ticket and link into this channel to stay on the line. But as I said first try to contact other developers. Maybe they simply integrate workarounds instead of that AFWall+ needs to add more rules over and over again with every new ROM. 

CK

**Closed** 2017-02-24 03:28 UTC
Labels: Review
