### ISSUE TITLE
afwall rules not reapplying on network change to data?

### ISSUE THREAD

**Issue by amihereidontknow** [ukanth/afwall#520] opened 2016-03-24 18:14 UTC
If I start my phone with wifi and data turned off and subsequently enable data, restricted apps can access data.

If I enable wifi, firewall seems to reapply without issue.

lg g3, vanilla CM12

**Comment by ukanth** [comment] 2016-03-25 09:28
I'm aware of this issue. It will be fixed in the next version.

**Comment by Gitoffthelawn** [comment] 2016-03-27 20:47
This issue is only a network data issue, and not a WiFi issue, correct?

IOW, users who boot with no network connectivity, but then enable WiFi after boot should be fine, correct?

**Comment by amihereidontknow** [comment] 2016-03-28 18:30
Yes, the issue is only for the network data. Enabling WiFi after boot is fine.

**Comment by Gitoffthelawn** [comment] 2016-03-28 22:18
@amihereidontknow Thanks.  Much appreciated.

**Comment by ukanth** [comment] 2016-03-29 04:50
can you post the steps to reproduce this issue with firewall rules (under menu-firewall rules). The issue I thought was different and not this.

**Comment by amihereidontknow** [comment] 2016-03-29 16:16
1) Turn network data off and reboot
2) After boot, enable network data

Tried WiFi to data switch but my phone seems unable to do that (seems to be problem with lg g3). Maybe that's the issue?

[rules.txt](https://github.com/ukanth/afwall/files/193814/rules.txt)

**Comment by amihereidontknow** [comment] 2016-03-31 16:49
It was ipv6 issue. I didn't know that my apn was set to tmo LTE ipv6. Now that I've changed apn to just regular tmo LTE, firewall is working great.

**Comment by Gitoffthelawn** [comment] 2016-04-01 01:58
@amihereidontknow Why would it not work with IPv6?  My understanding is that AFWall+ currently supports IPv6.

**Comment by amihereidontknow** [comment] 2016-04-01 08:45
I had the IPv6 setting disabled.

I enabled it to see if it fixes the initial issue but now the phone doesn't even connect to network data. If I disable the option, phone connects fine but the firewall doesn't reapply itself. I'm not even sure if this is afwall issue or just G3 and its usual LTE connectivity issue.

But for now changing APN to the regular one works fine.

**Comment by ukanth** [comment] 2016-04-01 08:57
There is a problem with IPV6 logic in current version which will be addressed in next version.

**Comment by eric93se** [comment] 2016-04-20 15:43
I have an LG G3 (D850) running turbo ROM and ACC Anykernel.  I use wifi only and the latest AFwall from f-droid (2.2.3), I have the same problem where the firewall will disable on its own.  I've always blocked captive portal login so I know if the firewall is working, I get an exclamation mark on the wifi icon.  This problem is new to this version for me.  I will revert back to 2.2.2 and report.

**Comment by eric93se** [comment] 2016-04-20 16:10
Using 2.2.2 and it seems to be good.  The only odd thing is I do not get a toast and sound when connecting to wifi (the OS warning of limited connection due to captive portal detection not connecting to the net) but this may be due to an update in the rom.  I do get the exclamation mark on the wifi signal icon and the firewall is working on apps.

I'm open for a test build if need be.   thanks!

**Closed as completed** 2016-08-03 06:07 UTC
Labels: Bug
