### ISSUE TITLE
Multi user hell ;(

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#535] opened 2016-06-09 18:49 UTC
Hi

I created a second user on my tablet (CM12) now none of my users have internet access on the same tablet.

What is the procedure to make sure the connections are firewalled and the net access is enabled for selected apps?

Am I supposed to install afwall on bot users?I did that and did not do anything. 

I cant find info on the wiki.

thanks

**Comment by ukanth** [comment] 2016-08-03 06:02
Duplicate of #271

**Closed as completed by ukanth** 2016-08-03 06:02 UTC
Labels: Feature
