### ISSUE TITLE
Ports forwarding GUI

### ISSUE THREAD

**Issue by Magissia** [ukanth/afwall#174] opened 2013-08-01 11:59 UTC
Hello, since AFwall+ is a firewall settings editor, wouldn't it be a logical thing to be able to do port forwarding with it ? 

For example, redirecting external port 22 to internal 2200, redirecting port 5000 to another ipadress etc.

I know i can use the custom script part, but we can also all create iptable rules from terminal, we're here because we want a GUI to make life simplier (because you don't know iptable commands by heart or whatever)

Every parts of my suggestion should be in a "port forwarding" page user could acces from menu > Ports forwarding and stuff would be shown as a table.

When creating a new rule, not writing destination ipadress would mean redirecting the port but keeping it on the device. (to not force user to write ::1 all the time)

I know it may sound crazy, but android isn't only used on phones, and even with that, it's clearly possible to recycle old phones as web servers, storage servers etc because today's phone are just isanly powerfull.

Regards

**Comment by ukanth** [comment] 2016-08-03 06:13
Duplicate of #15

**Closed by ukanth** 2016-08-03 06:13 UTC
Labels: Feature
