### ISSUE TITLE
com.android.providers.downloads denied

### ISSUE THREAD

**Issue by dstruck** [ukanth/afwall#662] opened 2017-01-16 17:14 UTC
When I launch adb logcat I observe that it gets spammed with the following messages from AFWall+ v2.9.1:
>[ 01-11 09:08:17.626 403: 403 W/afwallstart ]
type=1400 audit(0.0:296): avc: denied { getattr } for path="/data/data/com.android.providers.downloads" dev="dm-0" ino=65425 scontext=u:r:sysinit:s0 tcontext=ubject_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

>[ 01-11 09:08:18.626 403: 403 W/afwallstart ]
type=1400 audit(0.0:297): avc: denied { getattr } for path="/data/data/com.android.providers.downloads" dev="dm-0" ino=65425 scontext=u:r:sysinit:s0 tcontext=ubject_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

>[ 01-11 09:08:19.630 403: 403 W/afwallstart ]
type=1400 audit(0.0:298): avc: denied { getattr } for path="/data/data/com.android.providers.downloads" dev="dm-0" ino=65425 scontext=u:r:sysinit:s0 tcontext=ubject_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

This goes on indefinitely. Is this normal behaviour or is there some issue? 

I use AFWall+ v2.9.1 on an encrypted LG G4 with LineageOS 13.0. The xposed framework and GAPPS are not installed.

**Update:**
The comment from ElwOOd_CbGp on the XDA forum might be a clue about the cause of this issue:
>Just a guess but it looks like it may have something to do with the init script trying to access (avc: denied { getattr } for path="/data/data/com.android.providers.downloads" dev="dm-0") a new feature that was introduced one or two versions ago. If you have xposed framework installed, AFWall has the ability to block apps from using the system download manager. If you don't have xposed installed, that might be the reason for the warning message. I'm not a dev or involved with the development of AFWall so don't quote me. Just looking at the log entries, that's what I see. 
([source](https://forum.xda-developers.com/showpost.php?p=70566871&postcount=3584))

**Update 2:**
If I disable the "Fix startup data leak" option, the above log entries do not appear anymore.

**Comment by ukanth** [comment] 2017-02-24 02:53
AFWall+ startup script uses that location for init script. It has nothing to do with xposed/download related.

Seems like selinux it blocking AFWall+ from reading. I will keep this open and have a look

**Comment by GabryOryn** [comment] 2017-03-18 18:45
Same here, very huge battery drain. 
Slim 7.1.1 with microG. 

However I have found references to com.android.providers.download in etc/init.d/afwallstart but I do not know if it can hit something about the problem.

Thank you! 

![screenshot_20170318-194355](https://cloud.githubusercontent.com/assets/10218197/24074985/90b85e0a-0c13-11e7-8388-6c98df4d25ff.png)

**Comment by cpfeiffer** [comment] 2017-04-06 20:05
Same problem here. And indeed, disabling "Fix startup data leak" stops the message flood (one log entry per second!).

**Comment by vikputthiscodeongit** [comment] 2017-04-11 12:03
I can confirm that it's SELinux related. When setting SELinux from _Enforcing_ to _Permissive_ (in Resurrection Remix _Miscellaneous_ settings) the message is no longer being spammed to the logcat.

btw, I'm running RR 5.8.2 on a Xiaomi Mi 5

**Comment by haarp** [comment] 2017-05-14 08:29
Can also confirm this behavior.

Looking at the Startup data leak fix script, it appears to be waiting in an infinite loop until /data/data/com.android.providers.downloads is available and only then actually does anything. The loop never finishes if it can't stat that directory, so not only will there be constant, untraceable battery drain, the script will also not have any effect.

**Comment by jschbrt** [comment] 2017-07-06 16:26
Having this issue as well on my 6.0.1usimg Magisk with init.d Linker module. 
Does anyone has an idea how to solve it except of disabling the data startup leak fix?

**Comment by OhSoGood** [comment] 2017-10-07 15:06
Same here on Samsung S5 with Cyanogenmod 13.1

**Comment by krayon** [comment] 2017-10-29 09:45
In the event you have iptables/ip6tables in system/bin, you can skip over all the checking. Something like this should work:
    https://github.com/ukanth/afwall/compare/stable...krayon:wa-selinux

NOTE: This isn't the CLEANEST way to do it, just an edit with the least changes in case you're doing it manually through some crazy terminal on the machine. Also note that you may need to remount /system read-write to change the file:
```mount -o remount,rw /system```

**Comment by T-vK** [comment] 2018-01-30 09:16
I am having the same issue. My tablet sometimes only lasts 1-2 hours instead of days btw. I have not been able to find the cause, but it seems likely to be AfWall. 
I get the following message multiple times per second:  
`01-07 10:25:57.716   225   225 W afwallstart: type=1400 audit(0.0:741): avc: denied { getattr } for path="/data/data/com.android.providers.downloads" dev="mmcblk0p23" ino=114494 scontext=u:r:sysinit:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0`  
in logcat.

Disabling `com.android.providers.downloads` doesn't help btw (I still get the logcat messages).

My device:  
Lineage OS 13  
Android 7  
Nvidia Shield Tablet  
Afwall 2.9.7  

I also want to mention that I don't have GAPPS and I have microG installed.

**Comment by ukanth** [comment] 2021-03-07 13:13
Duplicate of #790

**Closed as completed by ukanth** 2021-03-07 13:13 UTC
Labels: Bug, Low
