### ISSUE TITLE
[Feature Request] Allow only specific IPs/Ports by App

### ISSUE THREAD

**Issue by TuxFighter** [ukanth/afwall#262] opened 2014-03-12 11:49 UTC
First of All, thanks for that nice App for Android.

One thing I currently miss at most is the possiblity to allow a specific app only to connect to a specific IP/Port. For example if I got a FTP client, which should only connect to ftp.mydomain.com, but not to a other domains/IPs. 

This would also be usefull to get rid of the fact, that much apps talking home. So to stick with the explaination above, we can be somewhat safer, that their isn´t any other connection from the app, which might smuggling any data to any other servers. This could really fight the fact that there are currently to much apps in the android ecosystem which are doing this.

For me it is really one of the most important feature for a firewall.

Thanks forward.

**Comment by ukanth** [comment] 2016-08-03 06:21
Duplicate of #15

**Closed by ukanth** 2016-08-03 06:21 UTC
Labels: Feature
